import { generatePdf } from './business-plan/export/pdf.ts';
import { generateXlsx } from './business-plan/export/xlsx.ts';

const SECTION_TITLES:any={executiveSummary:'Executive Summary',companyOverview:'Company Overview',productsServices:'Products & Services',marketAnalysis:'Industry & Market Analysis',targetMarket:'Target Market',competitiveAnalysis:'Competitive Analysis',marketingSales:'Marketing & Sales Strategy',operations:'Operations Plan',managementStaffing:'Management & Staffing',risks:'Risks & Mitigation',implementation:'Implementation Plan',funding:'Funding Requirement'};
const label=(key:string)=>key.replace(/([A-Z])/g,' $1').replace(/_/g,' ').replace(/^./,x=>x.toUpperCase());
const annual=(projection:any,key:string)=>[0,1,2].map(i=>Number(projection?.annual?.[i]?.[key]??0));
const rowsFrom=(rows:any[]=[], amountKey='amount')=>rows.map((row:any)=>({label:row.name||row.label||'Item',category:row.category||row.type||'',description:row.notes||'',type:row.type||'',timing:row.timing||'',amount:Number(row[amountKey]??0),annual:row.annual||[],monthly:row.monthly||[]}));
function statement(title:string,projection:any,key:string){const records=projection?.annual||[];const sample=records[0]?.[key]||{};return {title,lines:Object.keys(sample).filter(k=>typeof sample[k]==='number'&&k!=='balanceDifference').map(k=>({label:label(k),annual:[0,1,2].map(i=>Number(records[i]?.[key]?.[k]??0)),monthly:(projection?.monthly||[]).map((m:any)=>Number(m[key]?.[k]??0)),format:'currency'}))}}
function exportData(form:any,review:any){const p=review.projection,d=form.financialDraft||{},startup=Object.entries(d.startup||{}).filter(([,v])=>Number(v)>0).map(([k,v])=>({label:label(k),amount:Number(v)}));const sources=[{label:'Owner Investment',amount:Number(d.funding?.ownerInvestment||0)},{label:'Grant / Government Funding',amount:Number(d.funding?.grantGovernmentFunding||0)},...(d.loans||[]).map((x:any)=>({label:x.name||'Loan Financing',amount:Number(x.original_principal||0)}))].filter(x=>x.amount>0);const summaryKeys=['revenue','grossProfit','ebitda','netIncome','closingCash'];return {metadata:{planId:'local-plan',templateKey:'free-business-plan',templateVersion:'1',exportDate:new Date().toISOString(),currency:form.currency||'USD',projectionStartDate:review.assumptions?.projectionStartDate||'',snapshotId:'local',snapshotVersion:1,approvedSectionVersionIds:[]},business:{name:form.businessName||'Untitled Business',legalName:form.businessName,location:form.location,description:form.description,stage:form.businessStage,industry:form.industry,purpose:form.purpose,ownerName:form.ownerName},owners:form.ownerName?[{name:form.ownerName}]:[],sections:Object.entries(form.sections||{}).filter(([,x]:any)=>x.included&&x.content?.trim()).map(([key,x]:any)=>({key,title:SECTION_TITLES[key]||label(key),approvedVersionId:key,content:x.content,contentFormat:'markdown'})),financialSnapshot:{...review,currency:form.currency||'USD',projectionStartDate:review.assumptions?.projectionStartDate||'',snapshotVersion:1},financialSummary:summaryKeys.map(k=>({label:label(k),annual:annual(p,k),monthly:[],format:'currency'})),financialRatios:[],financialStatements:{income:statement('Income Statement',p,'incomeStatement'),cashFlow:statement('Cash Flow Statement',p,'cashFlowStatement'),balanceSheet:statement('Balance Sheet',p,'balanceSheet')},financialDetails:{revenue:rowsFrom(d.revenues,'price'),startupCosts:startup,funding:sources,operatingExpenses:rowsFrom(d.expenses),payroll:rowsFrom(d.staff,'salary_or_hourly_rate'),loans:rowsFrom(d.loans,'original_principal'),analysis:[],monthly:summaryKeys.map(k=>({label:label(k),annual:[],monthly:(p.monthly||[]).map((m:any)=>Number(m[k]??0)),format:'currency'})),assumptions:Object.entries({Currency:form.currency,...d.tax,...d.workingCapital}).map(([k,v])=>({label:label(k),description:String(v??'')}))},funding:{sources,uses:startup,totalSources:sources.reduce((s,x)=>s+x.amount,0),totalUses:startup.reduce((s,x)=>s+x.amount,0)},breakEven:review.analysis?.breakEven||{}} as any}
function save(bytes:Uint8Array,name:string,type:string){const copy=new Uint8Array(bytes);const blob=new Blob([copy.buffer],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const filename=(form:any,suffix:string)=>`${(form.businessName||'business-plan').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-${suffix}`;
export function downloadBusinessPlanPdf(form:any,review:any){save(generatePdf(exportData(form,review)),filename(form,'business-plan.pdf'),'application/pdf')}
export function downloadFinancialWorkbook(form:any,review:any){save(generateXlsx(exportData(form,review)),filename(form,'financial-projections.xlsx'),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}
