import test from 'node:test'; import assert from 'node:assert/strict'; import {BusinessPlanGenerationService,MemoryGenerationRepository} from '../src/lib/business-plan/generation-service.ts'; import {AI_CONFIG} from '../src/lib/business-plan/config.ts'; import {MAIN_SECTION_KEYS} from '../src/lib/business-plan/sections.ts';
const source:any={profile:{businessName:'Acme',description:'Consulting',stage:'Startup'},questionnaire:{owners:[{Name:'Owner'}],revenueStreams:[{Name:'Advice',Description:'Advisory'}],'What geographic market does the business serve?':'Local','Who are the indirect competitors?':'Internal teams','What marketing channels will be used?':'Referrals','Where will the business operate?':'Remote','Which work will be completed by the owners?':'Delivery','What are the main risks?':'Concentration'},approvedFinancial:{currency:'USD',annual:[{revenue:500000,ebitda:100000}],funding:{totalProjectCost:10},warnings:[]}};
const gate={allowed:true,reason:'approved'}; class FakeClient{calls=0;fail='';delay=0;async generate(){this.calls++;if(this.delay)await new Promise(r=>setTimeout(r,this.delay));if(this.fail)throw new Error(this.fail);return {content:'Narrative',factsUsed:[],financialFiguresUsed:[],warnings:[],inputTokens:100,outputTokens:50}}}
const setup=()=>{const repo=new MemoryGenerationRepository({p:'u',other:'v'}),client=new FakeClient(),service=new BusinessPlanGenerationService(repo,client as any);return {repo,client,service}};
test('initial generation makes one call, persists hash/version metadata and usage; cache makes zero calls',async()=>{const {repo,client,service}=setup(),first:any=await service.generate({userId:'u',planId:'p',key:'business_overview',source,gate});assert.equal(client.calls,1);assert.match(first.sourceDataHash,/^sha256-/);assert.equal(first.promptVersion,'1.0');assert.equal(repo.usage('p')[0].totalTokens,150);const cached:any=await service.generate({userId:'u',planId:'p',key:'business_overview',source,gate});assert.equal(cached.cacheHit,true);assert.equal(client.calls,1);assert.equal(repo.usage('p').length,1)});
test('explicit regeneration is one call and preserves prior version',async()=>{const {repo,client,service}=setup();await service.generate({userId:'u',planId:'p',key:'business_overview',source,gate});await service.generate({userId:'u',planId:'p',key:'business_overview',source,gate,regenerate:true});const section=repo.get('p','business_overview')!;assert.equal(client.calls,2);assert.equal(section.regenerationCount,1);assert.equal(repo.versions(section.id).length,1)});
test('manual edit and approval make zero calls; edit clears approval',async()=>{const {client,service}=setup();await service.generate({userId:'u',planId:'p',key:'business_overview',source,gate});service.approve('u','p','business_overview');service.saveEdit('u','p','business_overview','Owner edit');assert.equal(client.calls,1);const inspected=await service.inspect('u','p','business_overview',source,gate);assert.equal(inspected.section?.status,'edited');assert.equal(inspected.section?.isApproved,false)});
test('relevant change marks section outdated while payroll change does not',async()=>{const {service}=setup();await service.generate({userId:'u',planId:'p',key:'business_overview',source,gate});const payroll=structuredClone(source);payroll.questionnaire.positions=[{'Job title':'New'}];assert.notEqual((await service.inspect('u','p','business_overview',payroll,gate)).section?.status,'outdated');const profile=structuredClone(source);profile.profile.description='Changed';assert.equal((await service.inspect('u','p','business_overview',profile,gate)).section?.status,'outdated')});
test('gate, missing data, and cross-user access block before AI',async()=>{const {client,service}=setup();await assert.rejects(service.generate({userId:'u',planId:'p',key:'business_overview',source,gate:{allowed:false,reason:'financials_outdated'}}),/financials_outdated/);await assert.rejects(service.generate({userId:'v',planId:'p',key:'business_overview',source,gate}),/not_authorized/);const empty=structuredClone(source);empty.questionnaire.revenueStreams=[];await assert.rejects(service.generate({userId:'u',planId:'p',key:'products_services',source:empty,gate}),/section_information_incomplete/);assert.equal(client.calls,0)});
test('executive summary requires all other sections approved',async()=>{const {client,service}=setup();await assert.rejects(service.generate({userId:'u',planId:'p',key:'executive_summary',source,gate}),/executive_summary_requires_approved_sections/);assert.equal(client.calls,0);for(const key of MAIN_SECTION_KEYS){await service.generate({userId:'u',planId:'p',key,source,gate});service.approve('u','p',key)}await service.generate({userId:'u',planId:'p',key:'executive_summary',source,gate});assert.equal(client.calls,12)});
test('double click makes only one provider request',async()=>{const {client,service}=setup();client.delay=30;const one=service.generate({userId:'u',planId:'p',key:'business_overview',source,gate}),two=service.generate({userId:'u',planId:'p',key:'business_overview',source,gate});const results=await Promise.allSettled([one,two]);assert.equal(client.calls,1);assert.equal(results.filter(x=>x.status==='fulfilled').length,1)});
test('provider failure records error once, preserves content, and never retries',async()=>{const {repo,client,service}=setup();await service.generate({userId:'u',planId:'p',key:'business_overview',source,gate});client.fail='provider_error';await assert.rejects(service.generate({userId:'u',planId:'p',key:'business_overview',source,gate,regenerate:true}),/provider_error/);assert.equal(client.calls,2);assert.equal(repo.get('p','business_overview')?.generatedContent,'Narrative');assert.equal(repo.get('p','business_overview')?.status,'error');assert.equal(repo.usage('p').at(-1)?.requestStatus,'failed')});
test('regeneration limit blocks before provider call',async()=>{const {client,service}=setup();await service.generate({userId:'u',planId:'p',key:'business_overview',source,gate});for(let i=0;i<AI_CONFIG.maxRegenerationsPerSection;i++)await service.generate({userId:'u',planId:'p',key:'business_overview',source,gate,regenerate:true});await assert.rejects(service.generate({userId:'u',planId:'p',key:'business_overview',source,gate,regenerate:true}),/regeneration_limit/);assert.equal(client.calls,1+AI_CONFIG.maxRegenerationsPerSection)});
