import test from 'node:test';import assert from 'node:assert/strict';
import {BUSINESS_PLAN_EDITOR_SECTIONS} from '../src/lib/business-plan/sections.ts';
import {buildBusinessPlanExportData,generateDocx,generatePdf,generateXlsx,calculatePlanExportHash,BusinessPlanExportService,MemoryPrivateExportStorage,safeFilePart,type ExportRecord,type ExportSource} from '../src/lib/business-plan/export/index.ts';

const text=(v:Uint8Array)=>new TextDecoder().decode(v);
function source(overrides:Partial<ExportSource>={}):ExportSource{const annual=[1,2,3].map((year,i)=>({projectionYear:year,revenue:500000+i*100000,grossProfit:350000+i*50000,grossMargin:.7,ebitda:100000+i*10000,ebitdaMargin:.2,netIncome:i===0?-25000:80000,netMargin:i===0?-.05:.13,closingCash:90000+i*20000,totalAssets:250000,totalLiabilities:100000,totalEquity:150000,endingDebt:80000,debtService:24000,dscr:1.5}));const periods=annual.map((a,i)=>({incomeStatement:{revenue:a.revenue,grossProfit:a.grossProfit,grossMargin:a.grossMargin,ebitda:a.ebitda,netIncome:a.netIncome},cashFlowStatement:{netIncome:a.netIncome,netChangeInCash:10000,openingCash:80000,closingCash:a.closingCash},balanceSheet:{cash:a.closingCash,totalAssets:a.totalAssets,totalLiabilities:a.totalLiabilities,totalEquity:a.totalEquity,totalLiabilitiesAndEquity:a.totalAssets,balanceDifference:0},label:`Year ${i+1}`}));const sections=BUSINESS_PLAN_EDITOR_SECTIONS.map(([key,title],i)=>({key,title,status:'approved',isApproved:true,approvedContentVersionId:`version-${i}`,versions:[{id:`draft-${i}`,content:'Unapproved original'},{id:`version-${i}`,content:`Approved edited ${title} with **bold** content.`}]}));return {userId:'user-a',planId:'plan-a',business:{name:'Smith & Sons / Toronto Inc.',location:'Toronto, Canada'},sections,financialSnapshot:{id:'snapshot-1',businessPlanId:'plan-a',snapshotVersion:3,financialModelVersion:'1.2',financialAnalysisVersion:'1',assumptionsHash:'sha256-current',snapshotStatus:'approved',approvedAt:'2026-08-12T00:00:00Z',approvedBy:'user-a',projectionStartDate:'2026-01-01',projectionMonths:36,currency:'CAD',assumptionsJson:{fundingSources:[{label:'Owner Contribution',amount:50000}],projectCosts:[{label:'Equipment',amount:20000}]},projectionJson:{annual,monthly:Array.from({length:36},(_,i)=>({revenue:1000+i,netIncome:i===0?-25000:100}))},statementsJson:{annual:periods,monthly:periods},analysisJson:{annual,breakEven:{breakEvenRevenue:300000,firstBreakEvenMonth:8}},warningsJson:[],warningCodesAcknowledged:[]},currentFinancialHash:'sha256-current',readiness:{readyForExport:true,financialsApproved:true,totalSections:12,generatedSections:12,approvedSections:12,outdatedSections:0,missingSections:0,blockingReasons:[],planStatus:'approved_for_export'},...overrides};}

test('central builder selects only approved versions and immutable snapshot values',()=>{const data=buildBusinessPlanExportData(source(),new Date('2026-08-12T00:00:00Z'));assert.match(data.sections[0].content,/Approved edited/);assert.doesNotMatch(data.sections[0].content,/Unapproved/);assert.equal(data.financialSummary.find(x=>x.label==='Revenue')?.annual[0],500000);assert.equal(data.financialRatios.find(x=>x.label==='Debt Service Coverage Ratio')?.annual[0],1.5);assert.equal(data.financialRatios.find(x=>x.label==='Gross Margin')?.format,'percent');assert.equal(data.metadata.snapshotVersion,3);assert.equal(data.financialDetails.monthly[0].monthly.length,36)});
test('readiness, outdated financials, and unapproved content block before generation',()=>{assert.throws(()=>buildBusinessPlanExportData(source({readiness:{...source().readiness,readyForExport:false,blockingReasons:[{code:'SECTION_OUTDATED',sectionKey:'executive_summary'}]}})),/SECTION_OUTDATED/);assert.throws(()=>buildBusinessPlanExportData(source({currentFinancialHash:'different'})),/FINANCIALS_NOT_CURRENT/);const bad=source();bad.sections[0].isApproved=false;assert.throws(()=>buildBusinessPlanExportData(bad),/SECTION_NOT_APPROVED/)});
test('DOCX PDF and XLSX are valid deterministic containers with approved content and values',()=>{const data=buildBusinessPlanExportData(source()),docx=generateDocx(data),pdf=generatePdf(data),xlsx=generateXlsx(data);assert.deepEqual([...docx.slice(0,2)],[80,75]);assert.match(text(docx),/Approved edited Executive Summary/);assert.doesNotMatch(text(docx),/Unapproved original/);assert.match(text(pdf),/^%PDF-1.7/);assert.match(text(pdf),/Smith & Sons/);assert.deepEqual([...xlsx.slice(0,2)],[80,75]);assert.match(text(xlsx),/Monthly Projections/);assert.match(text(xlsx),/<v>500000<\/v>/);assert.match(text(xlsx),/<v>-25000<\/v>/);assert.match(text(xlsx),/<v>0.7<\/v>/)});
test('safe filenames preserve display name separately and remove filesystem characters',()=>{assert.equal(safeFilePart('Smith & Sons / Toronto Inc.'),'Smith_Sons_Toronto_Inc');assert.equal(buildBusinessPlanExportData(source()).business.name,'Smith & Sons / Toronto Inc.')});
test('hash changes only with approved sources and template identity',async()=>{const a=source(),hash=await calculatePlanExportHash(a),again=await calculatePlanExportHash(a);assert.equal(hash,again);a.sections[0].versions.find(x=>x.id===a.sections[0].approvedContentVersionId)!.content+=' changed';assert.notEqual(hash,await calculatePlanExportHash(a))});
test('service caches unchanged exports, versions changed exports, keeps private keys, and makes zero AI calls',async()=>{const rows:ExportRecord[]=[];let current=source();const repo={async loadSource(user:string,plan:string){if(user!==current.userId||plan!==current.planId)throw new Error('not_authorized');return current},async list(plan:string){return rows.filter(x=>x.businessPlanId===plan)},async save(r:ExportRecord){const i=rows.findIndex(x=>x.id===r.id);i<0?rows.push(structuredClone(r)):rows[i]=structuredClone(r)},async ownsExport(user:string,plan:string,id:string){return user===current.userId&&rows.some(x=>x.id===id&&x.businessPlanId===plan)}};const storage=new MemoryPrivateExportStorage(),service=new BusinessPlanExportService(repo,storage,()=>new Date('2026-08-12T00:00:00Z'));const first=await service.generate('user-a','plan-a','pdf'),cached=await service.generate('user-a','plan-a','pdf');assert.equal(first.exportVersion,1);assert.equal(cached.cached,true);assert.equal(rows.length,1);assert.match(first.storageKey,/^business-plan-exports\/plan-a\/v1\//);current=source();current.sections[0].versions.find(x=>x.id===current.sections[0].approvedContentVersionId)!.content+=' changed';const second=await service.generate('user-a','plan-a','pdf');assert.equal(second.exportVersion,2);assert.equal(rows[0].status,'superseded');const download=await service.createDownload('user-a','plan-a',second.id);assert.equal(download.expiresAt,'2026-08-12T00:10:00.000Z');await assert.rejects(()=>service.generate('user-b','plan-a','pdf'),/not_authorized/)});
test('optional structured datasets may be empty',()=>{const data=buildBusinessPlanExportData(source({details:{revenue:[],startupCosts:[],funding:[],operatingExpenses:[],payroll:[],loans:[],analysis:[],monthly:[]}}));assert.ok(generateXlsx(data).length>100)});
