import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateFinancialProjection } from '../src/financial-engine.ts';
import { calculateFinancialAnalysis } from '../src/financial-analysis.ts';
import { calculateFinancialAssumptionsHash, deriveFinancialStatus, FinancialApprovalStore, canGenerateBusinessPlan, getApprovedFinancialContext } from '../src/financial-review.ts';

const assumptions=(revenue=100)=>({planId:'plan-a',projectionStartDate:'2026-08-01',projectionMonths:36,currency:'USD',openingCash:50000,revenueStreams:[{id:'r1',name:'Services',startMonth:1,unitPrice:revenue,monthlyUnits:100}],directCostAssumptions:[{revenueStreamId:'r1',percentage:20}],startupProjectCosts:[],operatingExpenses:[],payrollAssumptions:[],fundingSources:[{id:'f1',name:'Owner',type:'owner_contribution',amount:50000,month:1}],loanAssumptions:[],taxAssumptions:{incomeTaxRate:0},depreciationAssumptions:{assets:[]},workingCapitalAssumptions:{useWorkingCapital:false}});
async function review(revenue=100){const a=assumptions(revenue);const projection=calculateFinancialProjection(a);return {assumptions:a,projection,analysis:calculateFinancialAnalysis(projection),assumptionsHash:await calculateFinancialAssumptionsHash(a),complete:true};}

test('SHA-256 assumptions hash is stable, order independent, and financially sensitive',async()=>{const a=assumptions(),b=structuredClone(a);b.fundingSources.reverse();b.revenueStreams[0].id='unimportant-id';assert.equal(await calculateFinancialAssumptionsHash(a),await calculateFinancialAssumptionsHash(b));assert.notEqual(await calculateFinancialAssumptionsHash(a),await calculateFinancialAssumptionsHash(assumptions(101)));});
test('all deterministic financial statuses and generation gates',()=>{const base={complete:true,errors:0,currentHash:'a'};assert.equal(deriveFinancialStatus({...base,complete:false}),'incomplete');assert.equal(deriveFinancialStatus({...base,calculating:true}),'calculating');assert.equal(deriveFinancialStatus({...base,errors:1}),'requires_correction');assert.equal(deriveFinancialStatus(base),'ready_for_review');const latestSnapshot={assumptionsHash:'a'};assert.equal(deriveFinancialStatus({...base,latestSnapshot}),'approved');assert.equal(deriveFinancialStatus({...base,currentHash:'b',latestSnapshot}),'outdated');for(const status of ['incomplete','calculating','requires_correction','ready_for_review','outdated'])assert.equal(canGenerateBusinessPlan(status).allowed,false);assert.deepEqual(canGenerateBusinessPlan('approved'),{allowed:true,reason:'approved'});});
test('approval requires warning acknowledgement and is idempotent',async()=>{const store=new FinancialApprovalStore(),r=await review();r.analysis.warnings.push({severity:'warning',code:'TEST_WARNING',title:'Review',message:'Review it',reviewArea:'Review'});assert.throws(()=>store.approve({planId:'plan-a',userId:'user-a',review:r,expectedHash:r.assumptionsHash,warningsAcknowledged:false}),/acknowledge/);const one=store.approve({planId:'plan-a',userId:'user-a',review:r,expectedHash:r.assumptionsHash,warningsAcknowledged:true,now:'2026-08-12T00:00:00Z'});const duplicate=store.approve({planId:'plan-a',userId:'user-a',review:r,expectedHash:r.assumptionsHash,warningsAcknowledged:true});assert.equal(one.snapshotVersion,1);assert.equal(duplicate.id,one.id);assert.equal(store.history('plan-a','user-a').length,1);});
test('blocking errors and stale clients cannot approve',async()=>{const store=new FinancialApprovalStore(),r=await review();r.analysis.warnings.push({severity:'error',code:'BLOCK',title:'Block',message:'No',reviewArea:'Review'});assert.throws(()=>store.approve({planId:'plan-a',userId:'user-a',review:r,expectedHash:r.assumptionsHash,warningsAcknowledged:true}),/Blocking/);const clean=await review();assert.throws(()=>store.approve({planId:'plan-a',userId:'user-a',review:clean,expectedHash:'old',warningsAcknowledged:true}),/changed while/);});
test('reapproval preserves immutable historical versions and enforces ownership',async()=>{const store=new FinancialApprovalStore(),r1=await review();const s1=store.approve({planId:'plan-a',userId:'user-a',review:r1,expectedHash:r1.assumptionsHash,warningsAcknowledged:true});const r2=await review(110);const s2=store.approve({planId:'plan-a',userId:'user-a',review:r2,expectedHash:r2.assumptionsHash,warningsAcknowledged:true});assert.equal(s2.snapshotVersion,2);assert.equal((store.view(s1.id,'user-a').projectionJson).annual[0].revenue,r1.projection.annual[0].revenue);assert.throws(()=>store.view(s1.id,'user-b'),/authorized/);});
test('approved context is compact, approved-only, and rejects outdated assumptions',async()=>{const store=new FinancialApprovalStore(),r=await review();const snapshot=store.approve({planId:'plan-a',userId:'user-a',review:r,expectedHash:r.assumptionsHash,warningsAcknowledged:true});const context=getApprovedFinancialContext(snapshot,r.assumptionsHash);assert.equal(context.annual.length,3);assert.equal('monthly' in context,false);assert.throws(()=>getApprovedFinancialContext(snapshot,'different'),/outdated/);});
