create type public.plan_payment_status as enum ('checkout_started','paid','payment_failed','refunded','disputed');
create type public.plan_entitlement_status as enum ('active','suspended','revoked');
create table public.stripe_customers(user_id uuid primary key references auth.users(id) on delete cascade,stripe_customer_id text not null unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.payments(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),business_plan_id uuid not null references public.business_plans(id),product_key text not null,stripe_customer_id text,stripe_checkout_session_id text not null unique,stripe_payment_intent_id text unique,stripe_charge_id text,stripe_price_id text not null,amount bigint check(amount>=0),currency text,payment_status public.plan_payment_status not null default 'checkout_started',paid_at timestamptz,refunded_at timestamptz,refund_amount bigint not null default 0 check(refund_amount>=0),dispute_status text,receipt_url text,metadata_json jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index payments_user_created_idx on public.payments(user_id,created_at desc);create index payments_plan_idx on public.payments(business_plan_id);
create table public.plan_entitlements(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),business_plan_id uuid not null references public.business_plans(id),entitlement_key text not null,source_type text not null check(source_type in ('payment','subscription','admin_grant','promotion')),source_payment_id uuid references public.payments(id),status public.plan_entitlement_status not null,granted_at timestamptz not null default now(),revoked_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,business_plan_id,entitlement_key,source_payment_id));
create index active_plan_entitlements_idx on public.plan_entitlements(user_id,business_plan_id,entitlement_key) where status='active';
create table public.stripe_webhook_events(stripe_event_id text primary key,event_type text not null,processing_status text not null check(processing_status in ('processing','processed','failed')),processed_at timestamptz,error_message text,created_at timestamptz not null default now());
alter table public.stripe_customers enable row level security;alter table public.payments enable row level security;alter table public.plan_entitlements enable row level security;alter table public.stripe_webhook_events enable row level security;
create policy "customers read own" on public.stripe_customers for select using(auth.uid()=user_id);create policy "payments read own" on public.payments for select using(auth.uid()=user_id);create policy "entitlements read own" on public.plan_entitlements for select using(auth.uid()=user_id);
-- No client write policies: payment and entitlement writes require the service role.
