import { calculateSectionSourceHash } from './hash.ts';
import { buildSectionContext, type PlanSource } from './context/index.ts';
import { BUSINESS_PLAN_EDITOR_SECTIONS, SECTION_DEPENDENCIES, type SectionKey, type SectionStatus } from './sections.ts';
import type { GenerationRepository, PlanSection, SectionVersion } from './generation-service.ts';

export const MAX_SECTION_CHARACTERS = 50_000;
export type EditorVersionType = SectionVersion['generationType'];
export type SourceStatus = {status:'current'|'outdated'|'missing_dependency'; changedDependencies:string[]; currentHash:string};
export type BlockingReason = {code:'FINANCIALS_NOT_CURRENT'|'SECTION_MISSING'|'SECTION_OUTDATED'|'SECTION_ERROR'|'SECTION_NOT_APPROVED';sectionKey?:SectionKey};
export type BusinessPlanReadiness = {readyForExport:boolean;financialsApproved:boolean;totalSections:number;generatedSections:number;approvedSections:number;outdatedSections:number;missingSections:number;blockingReasons:BlockingReason[];planStatus:'not_started'|'in_progress'|'ready_for_final_review'|'approved_for_export'|'requires_update'};

const currentContent=(section?:PlanSection)=>section?.editedContent || section?.generatedContent || '';
const clean=(content:string)=>content.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<[^>]+>/g,'').replace(/javascript:/gi,'');

export class BusinessPlanEditorService {
  private repository:GenerationRepository;
  constructor(repository:GenerationRepository){this.repository=repository}
  private authorize(userId:string,planId:string){if(!this.repository.ownsPlan(userId,planId))throw new Error('not_authorized')}
  private version(section:PlanSection,userId:string,type:EditorVersionType,content=currentContent(section),sourceHash=section.sourceDataHash){
    const versions=this.repository.versions(section.id), number=versions.length+1;
    const row:SectionVersion={id:`${section.id}-v${number}`,sectionId:section.id,versionNumber:number,content,sourceDataHash:sourceHash||'manual',generationType:type,promptVersion:section.promptVersion||'manual',modelUsed:section.modelUsed||'',inputTokens:0,outputTokens:0,estimatedCost:0,createdAt:new Date().toISOString(),createdBy:userId};
    this.repository.addVersion(row); return row;
  }
  list(userId:string,planId:string){this.authorize(userId,planId);return BUSINESS_PLAN_EDITOR_SECTIONS.map(([key,title])=>({key,title,section:this.repository.get(planId,key)}))}
  history(userId:string,planId:string,key:SectionKey){this.authorize(userId,planId);const section=this.repository.get(planId,key);return section?this.repository.versions(section.id):[]}
  async sourceStatus(userId:string,planId:string,key:SectionKey,source:PlanSource):Promise<SourceStatus>{this.authorize(userId,planId);const section=this.repository.get(planId,key),context=buildSectionContext(key,source),currentHash=await calculateSectionSourceHash(key,context);if(!section)return {status:'missing_dependency',changedDependencies:[],currentHash};return {status:section.sourceDataHash===currentHash?'current':'outdated',changedDependencies:section.sourceDataHash===currentHash?[]:[...SECTION_DEPENDENCIES[key]],currentHash}}
  async writeManually(userId:string,planId:string,key:SectionKey,source:PlanSource){this.authorize(userId,planId);if(this.repository.get(planId,key))throw new Error('section_exists');const hash=await calculateSectionSourceHash(key,buildSectionContext(key,source)),now=new Date().toISOString();const section:PlanSection={id:`${planId}-${key}`,planId,sectionKey:key,status:'edited',generatedContent:'',editedContent:'',sourceDataHash:hash,promptVersion:'manual',modelUsed:'',generationCount:0,regenerationCount:0,generatedAt:'',lastEditedAt:now,isApproved:false,inputTokens:0,outputTokens:0,estimatedCost:0,revision:1};this.repository.save(section);return section}
  save(userId:string,planId:string,key:SectionKey,content:string,expectedRevision:number){this.authorize(userId,planId);const section=this.repository.get(planId,key);if(!section)throw new Error('section_not_found');if(section.revision!==expectedRevision)throw new Error('stale_section');const safe=clean(content).trim();if(safe.length>MAX_SECTION_CHARACTERS)throw new Error('content_too_large');if(currentContent(section)!==safe)this.version(section,userId,'manual_edit');section.editedContent=safe;section.status='edited';section.isApproved=false;section.approvedAt=undefined;section.approvedBy=undefined;section.approvedContentVersionId=undefined;section.lastEditedAt=new Date().toISOString();section.revision++;this.repository.save(section);return section}
  async markReviewed(userId:string,planId:string,key:SectionKey,source:PlanSource,confirmed:boolean){this.authorize(userId,planId);if(!confirmed)throw new Error('review_confirmation_required');const section=this.repository.get(planId,key);if(!section||!currentContent(section))throw new Error('section_not_found');const hash=await calculateSectionSourceHash(key,buildSectionContext(key,source));section.sourceDataHash=hash;section.status='edited';section.isApproved=false;section.approvedAt=undefined;section.sourceReviewedAt=new Date().toISOString();section.sourceReviewedBy=userId;section.revision++;this.version(section,userId,'manual_review_refresh',currentContent(section),hash);this.repository.save(section);return section}
  approve(userId:string,planId:string,key:SectionKey){this.authorize(userId,planId);const section=this.repository.get(planId,key);if(!section||!currentContent(section).trim()||section.status==='outdated'||section.status==='error')throw new Error('section_not_approvable');if(section.isApproved)return section;const version=this.version(section,userId,'approval_snapshot');section.isApproved=true;section.status='approved';section.approvedAt=new Date().toISOString();section.approvedBy=userId;section.approvedContentVersionId=version.id;section.revision++;this.repository.save(section);return section}
  reopen(userId:string,planId:string,key:SectionKey){this.authorize(userId,planId);const section=this.repository.get(planId,key);if(!section)throw new Error('section_not_found');section.isApproved=false;section.approvedAt=undefined;section.status='edited';section.revision++;this.repository.save(section);return section}
  restore(userId:string,planId:string,key:SectionKey,versionId:string){this.authorize(userId,planId);const section=this.repository.get(planId,key);if(!section)throw new Error('section_not_found');const selected=this.repository.versions(section.id).find(v=>v.id===versionId);if(!selected)throw new Error('version_not_found');this.version(section,userId,'restored_version');section.editedContent=selected.content;section.isApproved=false;section.approvedAt=undefined;section.status=selected.sourceDataHash===section.sourceDataHash?'edited':'outdated';section.revision++;this.repository.save(section);return section}
  readiness(userId:string,planId:string,financialsApproved:boolean):BusinessPlanReadiness{this.authorize(userId,planId);const rows=BUSINESS_PLAN_EDITOR_SECTIONS.map(([key])=>[key,this.repository.get(planId,key)] as const),blockingReasons:BlockingReason[]=[];if(!financialsApproved)blockingReasons.push({code:'FINANCIALS_NOT_CURRENT'});for(const [key,s] of rows){if(!currentContent(s))blockingReasons.push({code:'SECTION_MISSING',sectionKey:key});else if(s!.status==='outdated')blockingReasons.push({code:'SECTION_OUTDATED',sectionKey:key});else if(s!.status==='error')blockingReasons.push({code:'SECTION_ERROR',sectionKey:key});if(!s?.isApproved)blockingReasons.push({code:'SECTION_NOT_APPROVED',sectionKey:key})}const generated=rows.filter(([,s])=>Boolean(currentContent(s))).length,approved=rows.filter(([,s])=>s?.isApproved).length,outdated=rows.filter(([,s])=>s?.status==='outdated').length,missing=rows.length-generated,readyForExport=!blockingReasons.length;const planStatus=readyForExport?'approved_for_export':outdated||!financialsApproved?'requires_update':generated===0?'not_started':missing===0?'ready_for_final_review':'in_progress';return {readyForExport,financialsApproved,totalSections:rows.length,generatedSections:generated,approvedSections:approved,outdatedSections:outdated,missingSections:missing,blockingReasons,planStatus}}
}
export const getCurrentSectionContent=currentContent;
