import { BUSINESS_PLAN_EDITOR_SECTIONS } from '../sections.ts';
import { BUSINESS_PLAN_EXPORT_TEMPLATE_KEY,BUSINESS_PLAN_EXPORT_TEMPLATE_VERSION } from './config.ts';
import type { BusinessPlanExportData,ExportLine,ExportSource,ExportTable } from './types.ts';

const obj=(v:unknown):any=>v&&typeof v==='object'?v:{}; const arr=(v:unknown):any[]=>Array.isArray(v)?v:[];
const number=(v:unknown):number|null=>typeof v==='number'&&Number.isFinite(v)?v:null;
const pick=(v:any,...keys:string[])=>{for(const k of keys)if(v?.[k]!==undefined&&v[k]!==null)return v[k]};
const annualValues=(annual:any[],keys:string[])=>[0,1,2].map(i=>number(pick(annual[i],...keys)));
const lines=(annual:any[],spec:Array<[string,string[],ExportLine['format']?]>):ExportLine[]=>spec.map(([label,keys,format])=>({label,annual:annualValues(annual,keys),monthly:[],format})).filter(x=>x.annual.some(v=>v!==null));
const statement=(title:string,value:any,nested?:string):ExportTable=>{const annual=arr(value?.annual??value),monthly=arr(value?.monthly),unwrap=(x:any)=>nested?obj(x?.[nested]):obj(x),first=unwrap(annual[0]),keys=Object.keys(first).filter(k=>typeof first[k]==='number'&&k!=='balanceDifference'&&!['changeInTaxPayable','taxPayable','currentPortionOfDebt','totalCurrentLiabilities','operatingExpenses','startupCosts'].includes(k));return {title,lines:keys.map(k=>({label:k.replace(/([A-Z])/g,' $1').replace(/_/g,' ').replace(/^./,c=>c.toUpperCase()),annual:[0,1,2].map(i=>number(unwrap(annual[i])?.[k])),monthly:monthly.map((x:any)=>number(unwrap(x)?.[k])??0),format:k.toLowerCase().includes('margin')?'percent':'currency'}))}}
export function getBusinessPlanReadiness(source:ExportSource){return source.readiness}
export function buildBusinessPlanExportData(source:ExportSource,now=new Date()):BusinessPlanExportData{
  const readiness=getBusinessPlanReadiness(source);if(!readiness.readyForExport)throw new Error(`export_not_ready:${readiness.blockingReasons.map(x=>`${x.code}${x.sectionKey?`:${x.sectionKey}`:''}`).join(',')}`);
  if(source.financialSnapshot.snapshotStatus!=='approved'||source.financialSnapshot.assumptionsHash!==source.currentFinancialHash)throw new Error('export_not_ready:FINANCIALS_NOT_CURRENT');
  const sections=BUSINESS_PLAN_EDITOR_SECTIONS.map(([key,title])=>{const section=source.sections.find(s=>s.key===key);if(!section?.isApproved||section.status!=='approved'||!section.approvedContentVersionId)throw new Error(`export_not_ready:SECTION_NOT_APPROVED:${key}`);const version=section.versions.find(v=>v.id===section.approvedContentVersionId);if(!version?.content.trim())throw new Error(`export_not_ready:SECTION_MISSING:${key}`);return {key,title,approvedVersionId:version.id,content:version.content,contentFormat:'markdown' as const}});
  const snapshot=source.financialSnapshot,projection=obj(snapshot.projectionJson),annual=arr(projection.annual),statements=obj(snapshot.statementsJson),analysis=obj(snapshot.analysisJson),assumptions=obj(snapshot.assumptionsJson);
  const summary=lines(annual,[['Revenue',['revenue','totalRevenue'],'currency'],['Gross Profit',['grossProfit'],'currency'],['Gross Margin',['grossMargin'],'percent'],['EBITDA',['ebitda'],'currency'],['EBITDA Margin',['ebitdaMargin'],'percent'],['Net Income',['netIncome'],'currency'],['Net Margin',['netMargin'],'percent'],['Closing Cash',['closingCash','cash'],'currency'],['Total Assets',['totalAssets'],'currency'],['Total Liabilities',['totalLiabilities'],'currency'],['Total Equity',['totalEquity'],'currency'],['Ending Debt',['endingDebt','debt'],'currency'],['Debt Service',['debtService'],'currency'],['DSCR',['dscr'],'ratio']]);
  const funding=obj(pick(projection,'funding')??pick(analysis,'funding')??assumptions.funding),sources=arr(pick(funding,'sources')??assumptions.fundingSources),uses=arr(pick(funding,'uses')??assumptions.projectCosts);
  const detail=source.details??{}, monthly=arr(projection.monthly);
  const financialRatios=lines(arr(analysis.annual).length?arr(analysis.annual):annual,[['Revenue Growth',['revenueGrowth'],'percent'],['Gross Margin',['grossMargin'],'percent'],['EBITDA Margin',['ebitdaMargin'],'percent'],['Net Margin',['netMargin'],'percent'],['Current Ratio',['currentRatio'],'ratio'],['Debt Service Coverage Ratio',['dscr'],'ratio'],['Working Capital',['workingCapital'],'currency']]);
  return {metadata:{planId:source.planId,templateKey:BUSINESS_PLAN_EXPORT_TEMPLATE_KEY,templateVersion:BUSINESS_PLAN_EXPORT_TEMPLATE_VERSION,exportDate:now.toISOString(),currency:snapshot.currency,projectionStartDate:snapshot.projectionStartDate,snapshotId:snapshot.id,snapshotVersion:snapshot.snapshotVersion,approvedSectionVersionIds:sections.map(s=>s.approvedVersionId)},business:source.business,owners:source.owners??[],sections,financialSnapshot:snapshot,financialSummary:summary,financialRatios,financialStatements:{income:statement('Projected Income Statement',statements,'incomeStatement'),cashFlow:statement('Projected Cash Flow Statement',statements,'cashFlowStatement'),balanceSheet:statement('Projected Balance Sheet',statements,'balanceSheet')},financialDetails:{revenue:detail.revenue??[],startupCosts:detail.startupCosts??uses, funding:detail.funding??sources,operatingExpenses:detail.operatingExpenses??[],payroll:detail.payroll??[],loans:detail.loans??[],analysis:detail.analysis??financialRatios,monthly:detail.monthly??Object.keys(obj(monthly[0])).filter(k=>typeof monthly[0]?.[k]==='number').map(k=>({label:k,monthly:monthly.map((m:any)=>m[k]),annual:[],format:'currency'}))},funding:{sources,uses,totalSources:number(pick(funding,'totalSources'))??undefined,totalUses:number(pick(funding,'totalUses'))??undefined,difference:number(pick(funding,'difference','surplusShortfall'))??undefined},breakEven:obj(pick(analysis,'breakEven')??pick(projection,'breakEven'))};
}
