import {display,stripMarkdown} from './format.ts';
import type {BusinessPlanExportData,ExportTable} from './types.ts';

type TextLine={text:string;x:number;y:number;size:number;font:'regular'|'bold';color?:string};
type PdfPage={lines:TextLine[];landscape?:boolean};
const ascii=(value:string)=>value.normalize('NFKD').replace(/[^\x20-\x7E]/g,' ').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
const wrap=(value:string,width:number)=>{const words=value.trim().split(/\s+/).filter(Boolean),lines:string[]=[];let line='';for(const word of words){if(!line)line=word;else if(`${line} ${word}`.length<=width)line+=` ${word}`;else{lines.push(line);line=word}}if(line)lines.push(line);return lines.length?lines:['']};

/** Build a readable, paginated business plan rather than writing a plain text dump. */
export function generatePdf(data:BusinessPlanExportData):Uint8Array{
  const bodyPages:PdfPage[]=[];
  const addPage=()=>{const page={lines:[]} as PdfPage;bodyPages.push(page);return page};
  const title=(page:PdfPage,text:string,subtitle?:string)=>{page.lines.push({text,x:48,y:742,size:22,font:'bold',color:'19324d'});if(subtitle)page.lines.push({text:subtitle,x:48,y:716,size:9,font:'regular',color:'5f7083'})};
  const addNarrative=(heading:string,content:string)=>{let page=addPage(),y=690;title(page,heading,'BUSINESS PLAN SECTION');for(const paragraph of stripMarkdown(content).split(/\n+/)){const rows=wrap(paragraph,92);if(y-rows.length*15<52){page=addPage();title(page,heading,'CONTINUED');y=690}for(const row of rows){page.lines.push({text:row,x:48,y,size:10,font:'regular',color:'283747'});y-=15}y-=9}};
  const addTable=(table:ExportTable)=>{let page=addPage(),y=690;title(page,table.title,'FINANCIAL PROJECTIONS');const header=()=>{page.lines.push({text:'Description',x:48,y,size:9,font:'bold'},{text:'Year 1',x:326,y,size:9,font:'bold'},{text:'Year 2',x:410,y,size:9,font:'bold'},{text:'Year 3',x:494,y,size:9,font:'bold'});y-=18};header();for(const line of table.lines){if(y<62){page=addPage();title(page,table.title,'FINANCIAL PROJECTIONS - CONTINUED');y=690;header()}page.lines.push({text:line.label.slice(0,48),x:48,y,size:9,font:'regular'});line.annual.slice(0,3).forEach((value,i)=>page.lines.push({text:display(value,line,data.metadata.currency),x:326+i*84,y,size:8,font:'regular'}));y-=17}};
  const addMonthlyTables=(table:ExportTable)=>{for(let year=0;year<3;year++){const page=addPage();page.landscape=true;let y=530;page.lines.push({text:data.business.name,x:30,y:577,size:10,font:'bold',color:'19324d'},{text:`Projected ${table.title} - Year ${year+1}`,x:30,y:558,size:16,font:'bold',color:'19324d'},{text:'Description',x:30,y,size:7,font:'bold'});const labels=(data.metadata.monthLabels||[]).slice(year*12,year*12+12);labels.forEach((label,i)=>page.lines.push({text:(label||`Month ${year*12+i+1}`).slice(0,9),x:250+i*42,y,size:6,font:'bold'}));page.lines.push({text:`Year ${year+1}`,x:754,y,size:6,font:'bold'});y-=14;for(const line of table.lines){if(y<42)break;page.lines.push({text:line.label.slice(0,36),x:30,y,size:6,font:'regular'});line.monthly.slice(year*12,year*12+12).forEach((value,i)=>page.lines.push({text:display(value,line,data.metadata.currency),x:250+i*42,y,size:5,font:'regular'}));page.lines.push({text:display(line.annual[year],line,data.metadata.currency),x:754,y,size:5,font:'bold'});y-=12}}};
  const sectionStarts:number[]=[];
  for(const section of data.sections){sectionStarts.push(bodyPages.length);addNarrative(section.title,section.content)}
  const financialStart=bodyPages.length;
  addTable({title:'Three-Year Financial Overview',lines:data.financialSummary});
  if(data.financialRatios.length)addTable({title:'Financial Ratios & Lending Metrics',lines:data.financialRatios});
  addTable(data.financialStatements.income);addMonthlyTables(data.financialStatements.income);addTable(data.financialStatements.cashFlow);addMonthlyTables(data.financialStatements.cashFlow);addTable(data.financialStatements.balanceSheet);addMonthlyTables(data.financialStatements.balanceSheet);
  const cover:PdfPage={lines:[{text:'BUSINESS PLAN',x:48,y:700,size:12,font:'bold',color:'2e67d1'},{text:data.business.name,x:48,y:630,size:30,font:'bold',color:'19324d'}]};
  const owner=(data.business as any).ownerName||data.business.preparedBy;if(owner)cover.lines.push({text:`Prepared by ${owner}`,x:48,y:588,size:11,font:'regular'});if(data.business.location)cover.lines.push({text:data.business.location,x:48,y:567,size:10,font:'regular'});cover.lines.push({text:new Date(data.metadata.exportDate).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'}),x:48,y:520,size:10,font:'regular'});
  const toc:PdfPage={lines:[]};title(toc,'Table of Contents','COMPLETE PLAN INDEX');let tocY=680;data.sections.forEach((section,i)=>{toc.lines.push({text:`${i+1}. ${section.title}`,x:58,y:tocY,size:10,font:'regular'},{text:String(sectionStarts[i]+3),x:530,y:tocY,size:10,font:'bold'});tocY-=25});toc.lines.push({text:`${data.sections.length+1}. Financial Projections`,x:58,y:tocY-5,size:10,font:'bold',color:'2e67d1'},{text:String(financialStart+3),x:530,y:tocY-5,size:10,font:'bold'});
  const pages=[cover,toc,...bodyPages],objects:string[]=[];const add=(s:string)=>{objects.push(s);return objects.length};const regular=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'),bold=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'),pageIds:number[]=[],contentIds:number[]=[];
  pages.forEach((page,index)=>{const commands=page.lines.map(line=>{const rgb=line.color?line.color.match(/../g)!.map(x=>parseInt(x,16)/255):[0.12,0.18,0.25];return `BT /${line.font==='bold'?'F2':'F1'} ${line.size} Tf ${rgb.map(x=>x.toFixed(3)).join(' ')} rg ${line.x} ${line.y} Td (${ascii(line.text)}) Tj ET`});commands.push(`BT /F1 8 Tf 0.35 0.4 0.46 rg 48 24 Td (Confidential) Tj ET`,`BT /F1 8 Tf 0.35 0.4 0.46 rg ${page.landscape?720:510} 24 Td (Page ${index+1}) Tj ET`);const stream=commands.join('\n');contentIds.push(add(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`));pageIds.push(add('PENDING'))});
  const pagesId=objects.length+1;pageIds.forEach((id,i)=>objects[id-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${pages[i].landscape?'792 612':'612 792'}] /Resources << /Font << /F1 ${regular} 0 R /F2 ${bold} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`);add(`<< /Type /Pages /Kids [${pageIds.map(x=>`${x} 0 R`).join(' ')}] /Count ${pageIds.length} >>`);const catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);let out='%PDF-1.7\n%TheBizPlans\n',offsets=[0];objects.forEach((object,i)=>{offsets.push(out.length);out+=`${i+1} 0 obj\n${object}\nendobj\n`});const xref=out.length;out+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(x=>`${String(x).padStart(10,'0')} 00000 n `).join('\n')}\ntrailer << /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(out)
}
