import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AlertTriangle, ArrowLeft, ArrowRight, BarChart3, Check, ChevronDown, CircleDollarSign, Copy, Download, FileChartColumn, FileSpreadsheet, FileText, PencilLine, Plus, Table2, Trash2, Users, X } from 'lucide-react';
import { annualize, financialAnalysis, loanSchedule, projectFinancials } from './finance.js';
import { calculatePayroll, DEPARTMENTS, normalizeStaffingPosition, validateStaffingPosition } from './payroll.ts';
import { calculateOperatingExpenses, EXPENSE_CATEGORIES, expenseCategoryLabel, normalizeOperatingExpense, validateOperatingExpense } from './operating-expenses.ts';
import { calculateFinancialProjection } from './financial-engine.ts';
import { calculateFinancialAnalysis } from './financial-analysis.ts';
import { calculateFinancialAssumptionsHash } from './financial-review.ts';
import { calculateLoanProjection, normalizeLoan, validateLoan, LOAN_TYPES } from './loans.ts';
import { incomeStatementDetailRows } from './financial-statement-labels.js';
import { downloadBusinessPlanPdf, downloadFinancialWorkbook } from './lib/free-exports.ts';
import './styles.css';

const money = n => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
const NAV=[['info','Business Information'],['plan','Business Plan'],['financials','Financial Projections'],['review','Review'],['download','Download']];
const PLAN_SECTIONS=[
 ['executiveSummary','Executive Summary','Provide a brief overview of the business, including what it does, target customers, competitive advantages, management, financing requirements and financial objectives.'],
 ['companyOverview','Company Overview','Describe the business structure, history, ownership, location, mission and the opportunity the business will pursue.'],
 ['productsServices','Products & Services','Explain the products or services offered, customer benefits, pricing, delivery and any future offerings.'],
 ['marketAnalysis','Industry & Market Analysis','Summarize the industry, market size, trends, regulations and evidence supporting demand.'],
 ['targetMarket','Target Market','Define your ideal customers, their needs, buying behavior, location and the segments you will prioritize.'],
 ['competitiveAnalysis','Competitive Analysis','Identify direct and indirect competitors and explain your practical, supportable competitive advantages.'],
 ['marketingSales','Marketing & Sales Strategy','Describe positioning, pricing, promotion, sales channels, customer acquisition and retention.'],
 ['operations','Operations Plan','Explain facilities, suppliers, technology, production, quality controls and daily workflows.'],
 ['managementStaffing','Management & Staffing','Introduce key leaders, responsibilities, relevant experience, staffing needs and hiring plans.'],
 ['risks','Risks & Mitigation','Identify important market, operational, financial and regulatory risks and how each will be managed.'],
 ['implementation','Implementation Plan','List the major milestones, owners, target dates and measures of progress.'],
 ['funding','Funding Requirement','State the amount and type of funding requested, planned use of funds and expected business impact.']
];
const defaults={businessName:'',ownerName:'',industry:'',location:'',businessStage:'New Business',startYear:String(new Date().getFullYear()),purpose:'Internal planning',description:'',currency:'USD',sections:Object.fromEntries(PLAN_SECTIONS.map(([key])=>[key,{content:'',included:true}]))};
function loadDraft(){try{return {...defaults,...JSON.parse(localStorage.getItem('free-business-plan-draft')||'{}')}}catch{return defaults}}
function App(){
 const [view,setView]=useState('landing'); const [form,setForm]=useState(loadDraft); const [financialReview,setFinancialReview]=useState(null); const [toast,setToast]=useState('');
 const update=(key,value)=>setForm(x=>({...x,[key]:value})); const updateFinancialDraft=useCallback(value=>setForm(x=>({...x,financialDraft:value})),[]);
 useEffect(()=>{try{localStorage.setItem('free-business-plan-draft',JSON.stringify(form))}catch{}},[form]);
 const go=v=>{setView(v);window.scrollTo(0,0)}; const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 if(view==='landing')return <Landing onStart={()=>go('info')}/>;
 return <div className="free-app"><header className="free-header"><Brand/><span>Free · no signup required</span></header><Flow view={view} go={go}/><main className="free-main">
  {view==='info'&&<BusinessInfo form={form} update={update} next={()=>go('plan')}/>}
  {view==='plan'&&<PlanEditor form={form} update={update} next={()=>go('financials')}/>}
  {view==='financials'&&<Financials setView={go} currency={form.currency} onCurrencyChange={v=>update('currency',v)} initialDraft={form.financialDraft} onDraftChange={updateFinancialDraft} onReviewChange={setFinancialReview}/>}
  {view==='review'&&<PlanReview form={form} review={financialReview} go={go}/>}
  {view==='download'&&<DownloadPage form={form} review={financialReview} back={()=>go('review')} notify={notify}/>}
 </main>{toast&&<div className="toast"><Check size={18}/>{toast}</div>}</div>
}
function Brand(){return <div className="public-brand"><div className="logo"><FileChartColumn/></div><div>Business Plan <b>Builder</b></div></div>}
function Landing({onStart}){return <div className="landing free-landing"><nav className="landing-nav"><Brand/><button className="primary" onClick={onStart}>Start My Free Plan</button></nav><section className="hero"><div className="hero-copy"><span className="hero-pill">100% FREE BUSINESS PLANNING TOOL</span><h1>Free Business Plan Generator</h1><p>Create a professional business plan and financial projections online for free. No signup required.</p><div className="hero-actions"><button className="primary hero-cta" onClick={onStart}>Build My Business Plan <ArrowRight/></button><span>No email · No payment · Your work stays in your browser</span></div><div className="hero-trust"><span><Check/>100% Free</span><span><Check/>Built-in Financial Projections</span><span><Check/>PDF & Excel Downloads</span></div></div><div className="plan-preview"><div className="preview-top"><FileChartColumn/><span>YOUR BUSINESS PLAN</span></div><h2>Your business, clearly planned.</h2><p>PROFESSIONAL BUSINESS PLAN</p><div className="preview-rule"/><div className="preview-content"><span>WHAT YOU GET</span><h3>A complete, editable plan you control.</h3>{['12 guided plan sections','36-month financial model','Professional PDF and Excel'].map(x=><p key={x}><Check size={16}/> {x}</p>)}</div></div></section><section className="included"><div className="section-heading"><span className="eyebrow">SIMPLE FIVE-STEP PROCESS</span><h2>From idea to downloadable plan</h2></div><div className="benefit-grid">{NAV.map(([,x],i)=><article className="card" key={x}><b>{i+1}</b><h3>{x}</h3><p>{['Add a few reusable business details.','Write or paste your content with practical guidance.','Build projections with the complete financial model.','Check the complete plan before export.','Download a business plan PDF and financial workbook.'][i]}</p></article>)}</div></section></div>}
function Flow({view,go}){const at=NAV.findIndex(([v])=>v===view);return <nav className="free-flow" aria-label="Business plan progress">{NAV.map(([v,label],i)=><button key={v} className={i===at?'active':i<at?'done':''} onClick={()=>go(v)}><span>{i<at?<Check/>:i+1}</span>{label}</button>)}</nav>}
function PageHead({eyebrow,title,copy}){return <div className="welcome"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div></div>}
function BusinessInfo({form,update,next}){return <div className="page"><PageHead eyebrow="STEP 1 OF 5" title="Business information" copy="Enter only the essentials. These details are reused on your cover page and throughout your downloads."/><section className="card info-card"><div className="field-grid"><Field label="Business Name" value={form.businessName} onChange={v=>update('businessName',v)} placeholder="Your business name"/><Field label="Owner / Founder Name" value={form.ownerName} onChange={v=>update('ownerName',v)} placeholder="Optional"/><Field label="Business Type / Industry" value={form.industry} onChange={v=>update('industry',v)} placeholder="e.g. Retail, consulting, restaurant"/><Field label="Business Location" value={form.location} onChange={v=>update('location',v)} placeholder="City, state/province, country"/><Select label="Business Stage" value={form.businessStage} options={['New Business','Existing Business']} onChange={v=>update('businessStage',v)}/><Field label="Business Start Year" value={form.startYear} onChange={v=>update('startYear',v)}/><Select label="Purpose of Business Plan" value={form.purpose} options={['Internal planning','Bank or lender','Investor funding','Grant application','Partner communication','Other']} onChange={v=>update('purpose',v)}/><div/></div><Field wide area label="Short Business Description" value={form.description} onChange={v=>update('description',v)} placeholder="In two or three sentences, describe what the business does and who it serves."/><div className="page-actions"><span>Saved automatically in this browser</span><button className="primary" onClick={next}>Continue to Business Plan <ArrowRight/></button></div></section></div>}
function PlanEditor({form,update,next}){const change=(key,patch)=>update('sections',{...form.sections,[key]:{...form.sections[key],...patch}});return <div className="page plan-editor-page"><PageHead eyebrow="STEP 2 OF 5" title="Write your business plan" copy="Use the guidance below, then write or paste your own content. No narrative content is generated for you."/><div className="editor-section-list">{PLAN_SECTIONS.map(([key,title,guidance],i)=>{const row=form.sections[key]||{content:'',included:true};return <section className="card direct-editor" key={key}><div className="direct-editor-head"><div><span>{String(i+1).padStart(2,'0')}</span><h2>{title}</h2></div><label className="include-toggle"><input type="checkbox" checked={row.included} onChange={e=>change(key,{included:e.target.checked})}/> Include in plan</label></div><p className="section-guidance">{guidance}</p><textarea value={row.content} onChange={e=>change(key,{content:e.target.value})} placeholder={`Write or paste your ${title.toLowerCase()} here…`} rows="8"/><small>{row.content.trim().split(/\s+/).filter(Boolean).length} words · Empty sections are excluded automatically.</small></section>})}</div><div className="sticky-next"><span>Your writing is saved locally as you work.</span><button className="primary" onClick={next}>Continue to Financial Projections <ArrowRight/></button></div></div>}
function Field({label,value,onChange,wide,area,placeholder}){return <div className={(wide?'wide ':'')+'field'}><label>{label}</label>{area?<textarea value={value??''} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>:<input value={value??''} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>}</div>}
function Select({label,value,options,onChange}){return <div className="field"><label>{label}</label><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(option=><option key={option} value={option}>{option}</option>)}</select></div>}
function Financials({setView,currency,onCurrencyChange,initialDraft,onDraftChange,onReviewChange}) {
  const formatMoney=value=>new Intl.NumberFormat(currency==='CAD'?'en-CA':'en-US',{style:'currency',currency,maximumFractionDigits:0}).format(value||0);
  const sections = [
    ['revenue','1','Revenue Assumptions','Pricing, demand and collection'],
    ['startup','2','Project Cost & Sources of Funds','Investment requirements, financing and opening cash'],
    ['expenses','3','Operating Expenses','Ongoing costs required to run the business'],
    ['payroll','4','Payroll & Staffing','Employees, owners and contractors'],
    ['loan','5','Loans & Debt Service','Existing and proposed business debt'],
    ['workingCapital','6','Working Capital','Collection, inventory and supplier timing'],
    ['fixedAssets','7','Fixed Assets & Depreciation','Capital purchases and straight-line depreciation'],
    ['outputs','8','Projection Preview','Monthly and annual diagnostics']
  ];
  const [active,setActive]=useState('revenue');
  const [revenues,setRevenues]=useState(()=>initialDraft?.revenues||[{name:'Creative services',price:85,units:120,year2Price:88,year2Units:140,year3Price:91,year3Units:165,growth:0,seasonal:0,annualPriceIncrease:0,directCost:28,paymentTiming:'Due on receipt',refundRate:1}]);
  const [startup,setStartup]=useState(()=>{const saved=initialDraft?.startup||{};const {initialCashBalance,workingCapital:legacyWorkingCapital,...current}=saved;return {businessPurchase:0,equipment:12000,furniture:3500,renovations:0,leaseholdImprovements:0,inventory:0,deposits:4000,website:2500,software:1200,legalFees:1800,accountingFees:1200,marketing:4500,licensing:600,insurance:1800,vehicle:0,otherCosts:0,...current,initialCashReserve:Number(saved.initialCashReserve??legacyWorkingCapital??0)};});
  const [funding,setFunding]=useState(()=>{const saved=initialDraft?.funding||{};const legacyOwnerInvestment=initialDraft?.startup?.initialCashBalance??initialDraft?.workingCapital?.openingCashInvestment??initialDraft?.openingCashInvestment??initialDraft?.initialCashBalance??0;return {ownerInvestment:Number(Object.hasOwn(saved,'ownerInvestment')?saved.ownerInvestment:legacyOwnerInvestment)+Number(saved.investorContribution||0),grantGovernmentFunding:Number(saved.grantGovernmentFunding??saved.grantOrOtherFunding??0)+Number(saved.otherFunding||0)};});
  const [expenses,setExpenses]=useState(()=>{
    const defaults=[
      {id:'rent',name:'Rent',category:'premises',amount:2400,frequency:'Monthly',startMonth:1,endMonth:36,annualIncrease:3,notes:''},
      {id:'software',name:'Software subscriptions',category:'software_and_technology',amount:650,frequency:'Monthly',startMonth:1,endMonth:36,annualIncrease:0,notes:''},
      {id:'marketing',name:'Marketing',category:'marketing',amount:1200,frequency:'Monthly',startMonth:1,endMonth:36,annualIncrease:0,notes:''}
    ];
    if(Array.isArray(initialDraft?.expenses))return initialDraft.expenses.map(normalizeOperatingExpense);
    try { const saved=JSON.parse(localStorage.getItem('thebizplans-operating-expenses')); return Array.isArray(saved)?saved.map(normalizeOperatingExpense):defaults; } catch { return defaults; }
  });
  const [staff,setStaff]=useState(()=>Array.isArray(initialDraft?.staff)?initialDraft.staff.map(normalizeStaffingPosition):(()=>{ try { const saved=JSON.parse(localStorage.getItem('thebizplans-staffing-positions')); return Array.isArray(saved)?saved.map(normalizeStaffingPosition):[]; } catch { return []; } })());
  const [loans,setLoans]=useState(()=>Array.isArray(initialDraft?.loans)?initialDraft.loans.map(normalizeLoan):(()=>{ try { const saved=JSON.parse(localStorage.getItem('thebizplans-loans')); return Array.isArray(saved)?saved.map(normalizeLoan):[]; } catch { return []; } })());
  const [workingCapital,setWorkingCapital]=useState(()=>{const {openingCashInvestment:legacyOpeningCash,...saved}=initialDraft?.workingCapital||{};return {useWorkingCapital:false,accountsReceivableDays:0,inventoryDays:0,accountsPayableDays:0,minimumInventoryBalance:0,notes:'',...saved};});
  const [assetLives,setAssetLives]=useState(()=>initialDraft?.assetLives||{equipment:60,furniture:60,renovations:120,leaseholdImprovements:120,vehicle:60});
  const [fixedAssets,setFixedAssets]=useState(()=>initialDraft?.fixedAssets||[]);
  const [tax,setTax]=useState(()=>initialDraft?.tax||{incomeTaxRate:12,salesTaxRate:8.875,depreciation:'Straight-line over 5 years',openingLosses:0,ownerDraws:3000});
  const updateObject=(setter,key,value)=>setter(current=>({...current,[key]:value}));
  const revenueMonthly=useMemo(()=>projectFinancials({revenues:revenues.map(row=>({...row,growth:Number(row.growth||0)/100,directCost:Number(row.directCost||0)/100})),expenses:0,payroll:0}).map(row=>row.revenue),[revenues]);
  const revenueStreams=useMemo(()=>revenues.map((row,index)=>({id:`revenue-${index}`,name:row.name||`Revenue stream ${index+1}`,monthly:projectFinancials({revenues:[{...row,growth:Number(row.growth||0)/100,directCost:Number(row.directCost||0)/100}],expenses:0,payroll:0}).map(month=>month.revenue)})),[revenues]);
  const expenseProjection=useMemo(()=>calculateOperatingExpenses(expenses,36,revenueMonthly,revenueStreams),[expenses,revenueMonthly,revenueStreams]);
  useEffect(()=>{ try { localStorage.setItem('thebizplans-operating-expenses',JSON.stringify(expenses)); } catch { /* Storage may be unavailable. */ } },[expenses]);
  useEffect(()=>{ try { localStorage.setItem('thebizplans-staffing-positions',JSON.stringify(staff)); } catch { /* Storage may be unavailable. */ } },[staff]);
  useEffect(()=>{ try { localStorage.setItem('thebizplans-loans',JSON.stringify(loans)); } catch { /* Storage may be unavailable. */ } },[loans]);
  useEffect(()=>{onDraftChange({revenues,startup,funding,expenses,staff,loans,workingCapital,assetLives,fixedAssets,tax})},[revenues,startup,funding,expenses,staff,loans,workingCapital,assetLives,fixedAssets,tax,onDraftChange]);
  const payrollProjection=useMemo(()=>calculatePayroll(staff),[staff]);
  const payroll=payrollProjection.monthly.map(row=>row.total_payroll);
  const openingCash=0;
  const depreciableAssets=Number(startup.equipment||0)+Number(startup.furniture||0)+Number(startup.renovations||0)+Number(startup.leaseholdImprovements||0)+Number(startup.vehicle||0);
  const months=useMemo(()=>projectFinancials({revenues:revenues.map(row=>({...row,growth:Number(row.growth||0)/100,directCost:Number(row.directCost||0)/100})),expenses:expenseProjection.monthly,payroll,openingCash,taxRate:tax.incomeTaxRate,depreciableAssets,ownerDraws:tax.ownerDraws,inventory:startup.inventory}),[revenues,expenseProjection.monthly,payroll,openingCash,tax.incomeTaxRate,tax.ownerDraws,depreciableAssets,startup.inventory]);
  const centralAssumptions=useMemo(()=>({planId:'demo-plan',projectionStartDate:'2026-08-01',projectionMonths:36,currency,openingCash,initialCashReserve:Number(startup.initialCashReserve||0),revenueStreams:revenues.map((row,index)=>({id:`revenue-${index}`,name:row.name,startMonth:1,unitPrice:Number(row.price||0),monthlyUnits:Number(row.units||0),unitPriceByYear:[row.price,row.year2Price??row.price,row.year3Price??row.year2Price??row.price].map(Number),monthlyUnitsByYear:[row.units,row.year2Units??row.units,row.year3Units??row.year2Units??row.units].map(Number),monthlyGrowthRate:Number(row.growth||0),annualPriceIncreaseRate:Number(row.annualPriceIncrease||0)})),directCostAssumptions:revenues.map((row,index)=>({revenueStreamId:`revenue-${index}`,percentage:Number(row.directCost||0)})),startupProjectCosts:Object.entries(startup).filter(([key,amount])=>!['workingCapital','initialCashBalance','initialCashReserve'].includes(key)&&Number(amount)>0).map(([key,amount])=>({id:`cost-${key}`,name:key.replace(/([A-Z])/g,' $1'),amount:Number(amount),paymentMonth:1,type:['equipment','furniture','renovations','leaseholdImprovements','vehicle'].includes(key)?'capital_expenditure':key==='inventory'?'opening_inventory':key==='deposits'?'deposit_or_prepaid':'startup'})),operatingExpenses:expenses,payrollAssumptions:staff,fundingSources:[{id:'owner-investment',name:'Owner investment',type:'owner_contribution',amount:Number(funding.ownerInvestment||0),month:1},{id:'grant-funding',name:'Grant / government funding',type:'grant',amount:Number(funding.grantGovernmentFunding||0),month:1}].filter(source=>source.amount>0),loanAssumptions:loans,taxAssumptions:{incomeTaxRate:Number(tax.incomeTaxRate||0),paymentLagMonths:1},depreciationAssumptions:{assets:[...([['equipment','Equipment'],['furniture','Furniture'],['renovations','Renovations'],['leaseholdImprovements','Leasehold improvements'],['vehicle','Vehicle']].filter(([key])=>Number(startup[key]||0)>0).map(([key,name])=>({id:`fixed-${key}`,name,category:key,purchaseAmount:Number(startup[key]),purchaseMonth:1,inServiceMonth:1,usefulLifeMonths:Number(assetLives[key]||60),residualValue:0,depreciationMethod:'straight_line',sourceStartupCostId:`cost-${key}`}))),...fixedAssets.filter(asset=>Number(asset.purchaseAmount)>0).map(asset=>({...asset,purchaseAmount:Number(asset.purchaseAmount),purchaseMonth:Math.max(1,Number(asset.purchaseMonth)||1),inServiceMonth:Math.max(1,Number(asset.purchaseMonth)||1),usefulLifeMonths:Math.max(1,Number(asset.usefulLifeMonths)||60),residualValue:0,depreciationMethod:'straight_line'}))]},workingCapitalAssumptions:workingCapital}),[revenues,expenses,staff,openingCash,loans,tax.incomeTaxRate,startup,funding,currency,workingCapital,assetLives,fixedAssets]);
  const centralProjection=useMemo(()=>calculateFinancialProjection(centralAssumptions),[centralAssumptions]);
  const centralAnalysis=useMemo(()=>calculateFinancialAnalysis(centralProjection),[centralProjection]);
  useEffect(()=>{let live=true;calculateFinancialAssumptionsHash(centralAssumptions).then(assumptionsHash=>live&&onReviewChange({assumptions:centralAssumptions,projection:centralProjection,analysis:centralAnalysis,assumptionsHash,complete:centralAssumptions.revenueStreams.every(row=>row.name&&row.monthlyUnits>0)}));return()=>{live=false}},[centralAssumptions,centralProjection,centralAnalysis,onReviewChange]);
  const years=annualize(months);
  const analysis=financialAnalysis(months);
  const fieldGrid=(values,setter,fields)=><div className="financial-field-grid">{fields.map(([key,label,suffix])=><Field key={key} label={label+(suffix?` (${suffix})`:'')} value={values[key]} onChange={value=>updateObject(setter,key,value)}/>)}</div>;
  const startupFields=[['businessPurchase','Business purchase / acquisition cost','$'],['equipment','Equipment','$'],['furniture','Furniture','$'],['renovations','Renovations','$'],['leaseholdImprovements','Leasehold improvements','$'],['inventory','Inventory','$'],['deposits','Deposits','$'],['website','Website','$'],['software','Software','$'],['legalFees','Legal fees','$'],['accountingFees','Accounting fees','$'],['marketing','Marketing','$'],['licensing','Licensing','$'],['insurance','Insurance','$'],['vehicle','Vehicle','$'],['otherCosts','Other project costs','$'],['initialCashReserve','Initial working capital / cash reserve','$']];
  const totalProjectCost=Object.entries(startup).reduce((sum,[key,value])=>sum+(['workingCapital','initialCashBalance'].includes(key)?0:Number(value||0)),0)+fixedAssets.reduce((sum,asset)=>sum+Number(asset.purchaseAmount||0),0);
  const proposedLoanFunding=loans.filter(loan=>(loan.loan_status??loan.existing_or_proposed)==='proposed').reduce((sum,loan)=>sum+Number(loan.original_principal||0),0);
  const totalFunding=Number(funding.ownerInvestment||0)+proposedLoanFunding+Number(funding.grantGovernmentFunding||0);
  const fundingPosition=totalFunding-totalProjectCost;
  const fundingPositionLabel=fundingPosition<0?'Funding Shortfall':fundingPosition>0?'Funding Surplus':'Fully Funded';
  const projectedOpeningCash=Math.max(0,totalFunding-(totalProjectCost-Number(startup.initialCashReserve||0)));
  return <div className="page financial-input-page"><div className="welcome"><div><span className="eyebrow">FINANCIAL INPUTS · 36-MONTH FORECAST</span><h1>Build your financial assumptions</h1><p>Enter distinct assumptions for each projection year; results update instantly.</p></div><div className="field currency-picker"><label>Projection currency</label><select value={currency} onChange={event=>onCurrencyChange(event.target.value)}><option value="USD">USD — US Dollar</option><option value="CAD">CAD — Canadian Dollar</option></select></div></div>
    <div className="finance-workspace"><nav className="finance-section-nav">{sections.map(([id,letter,title,caption])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}><span>{letter}</span><div><strong>{title}</strong><small>{caption}</small></div><ArrowRight size={15}/></button>)}</nav>
      <section className="finance-main"><div className="card financial-form"><div className="financial-form-head"><div><span className="eyebrow">{sections.find(x=>x[0]===active)[1]} · ASSUMPTIONS</span><h2>{sections.find(x=>x[0]===active)[2]}</h2><p>{sections.find(x=>x[0]===active)[3]}</p></div><span className="saved"><Check size={14}/>Saved automatically</span></div>
        {active==='revenue'&&<><div className="formula-callout"><b>Annual revenue assumptions</b><span>Set the monthly units and selling price independently for Years 1, 2 and 3.</span></div><div className="repeater">{revenues.map((row,index)=><div className="repeat-card" key={index}><div className="repeat-head"><h2>Revenue stream {index+1}</h2>{revenues.length>1&&<button onClick={()=>setRevenues(revenues.filter((_,i)=>i!==index))}><Trash2 size={16}/></button>}</div><div className="financial-field-grid"><Field label="Revenue stream name" value={row.name} onChange={value=>setRevenues(revenues.map((item,i)=>i===index?{...item,name:value}:item))}/>{[['price','Year 1 selling price'],['units','Year 1 monthly units'],['year2Price','Year 2 selling price'],['year2Units','Year 2 monthly units'],['year3Price','Year 3 selling price'],['year3Units','Year 3 monthly units'],['growth','Monthly growth within each year (%)'],['directCost','Direct cost percentage (%)'],['paymentTiming','Payment timing'],['refundRate','Refund or cancellation rate (%)']].map(([key,label])=><Field key={key} label={label} value={row[key]??''} onChange={value=>setRevenues(revenues.map((item,i)=>i===index?{...item,[key]:value}:item))}/>)}</div></div>)}</div><button className="add-row" onClick={()=>setRevenues([...revenues,{name:'New revenue stream',price:0,units:0,year2Price:0,year2Units:0,year3Price:0,year3Units:0,growth:0,directCost:0,paymentTiming:'Due on receipt',refundRate:0}])}><Plus size={16}/>Add revenue stream</button></>}
        {active==='startup'&&<div className="sources-uses-schedule"><div className="formula-callout"><b>Uses and sources are separate</b><span>The cash reserve is a project use. Enter only money contributed or financed as a source; opening cash is calculated separately.</span></div><section className="funding-section"><h3>A. Total Project Cost / Uses of Funds</h3><p className="section-helper">Enter every startup requirement, including the cash reserve needed when the business opens.</p>{fieldGrid(startup,setStartup,startupFields)}<div className="financial-total"><span>Total Project Cost</span><strong>{formatMoney(totalProjectCost)}</strong></div></section><section className="funding-section"><h3>B. Sources of Funds / Financing</h3><p className="section-helper">Identify where the money required to fund the project will come from.</p><div className="funding-source-grid"><Field label="Owner / Initial Equity Contribution ($)" value={funding.ownerInvestment} onChange={value=>updateObject(setFunding,'ownerInvestment',value)}/><div className="linked-funding-field"><span>Loan Financing ($)</span><div><strong>{formatMoney(proposedLoanFunding)}</strong><small>Automatically derived from Loans &amp; Debt Service</small></div></div><Field label="Grant / Government Funding ($)" value={funding.grantGovernmentFunding} onChange={value=>updateObject(setFunding,'grantGovernmentFunding',value)}/></div><div className="financial-total"><span>Total Sources of Funds</span><strong>{formatMoney(totalFunding)}</strong></div></section><section className="funding-section funding-position"><h3>C. Project Funding Position</h3><p className="section-helper">Compare the complete project requirement with the financing currently available.</p><dl className="funding-summary"><div><dt>Total Project Cost / Uses of Funds</dt><dd>{formatMoney(totalProjectCost)}</dd></div><div><dt>Less: Total Sources of Funds</dt><dd>{formatMoney(totalFunding)}</dd></div><div className={`position-result ${fundingPosition<0?'shortfall':fundingPosition>0?'surplus':'funded'}`}><dt>{fundingPositionLabel}</dt><dd>{formatMoney(Math.abs(fundingPosition))}</dd></div></dl><div className="cash-context"><div><span>Projected Opening Cash</span><strong>{formatMoney(projectedOpeningCash)}</strong></div><div><span>Target Opening Cash Reserve</span><strong>{formatMoney(Number(startup.initialCashReserve||0))}</strong></div><p>Projected opening cash is financing left after startup uses other than the requested cash reserve have been paid.</p></div></section></div>}
        {active==='expenses'&&<OperatingExpenses expenses={expenses} setExpenses={setExpenses} projection={expenseProjection} revenueMonthly={revenueMonthly} revenueStreams={revenueStreams} onPrevious={()=>setActive('startup')} onNext={()=>setActive('payroll')}/>}
        {active==='payroll'&&<PayrollStaffing currency={currency} positions={staff} setPositions={setStaff} projection={payrollProjection} onPrevious={()=>setActive('expenses')} onNext={()=>setActive('loan')}/>}
        {active==='loan'&&<LoanDebtService loans={loans} setLoans={setLoans} currency={currency} onPrevious={()=>setActive('payroll')} onNext={()=>setView('review')}/>}
        {active==='workingCapital'&&<><p>Enter optional assumptions for customer collection timing, inventory levels, and supplier payment timing. Leave disabled for immediate payment terms. Funding is entered in Project Cost & Sources of Funds; this section contains only operating working-capital assumptions.</p><label className="toggle-row"><input type="checkbox" checked={workingCapital.useWorkingCapital} onChange={e=>updateObject(setWorkingCapital,'useWorkingCapital',e.target.checked)}/> Enable Working Capital Adjustments</label>{fieldGrid(workingCapital,setWorkingCapital,[['accountsReceivableDays','Accounts Receivable Days'],['inventoryDays','Inventory Days'],['accountsPayableDays','Accounts Payable Days'],['minimumInventoryBalance','Minimum Inventory Balance','$'],['notes','Notes']])}</>}
        {active==='fixedAssets'&&<><p>Review capital purchases from Startup Costs or add another fixed asset, such as an office, property, or machinery. Straight-line depreciation is calculated automatically.</p>{[['equipment','Equipment'],['furniture','Furniture'],['renovations','Renovations'],['leaseholdImprovements','Leasehold improvements'],['vehicle','Vehicle']].filter(([key])=>Number(startup[key]||0)>0).map(([key,name])=><div className="repeat-card" key={key}><strong>{name} · {money(Number(startup[key]))}</strong><Field label="Useful life (months)" value={assetLives[key]} onChange={value=>updateObject(setAssetLives,key,value)}/><small>Purchase amount is linked to Startup Costs and cannot be edited here.</small></div>)}{fixedAssets.map((asset,index)=><div className="repeat-card" key={asset.id}><div className="repeat-head"><h2>Additional fixed asset {index+1}</h2><button aria-label={`Remove ${asset.name||'fixed asset'}`} onClick={()=>setFixedAssets(fixedAssets.filter((_,i)=>i!==index))}><Trash2 size={16}/></button></div><div className="financial-field-grid">{[['name','Asset name'],['category','Asset category'],['purchaseAmount','Purchase amount ($)'],['purchaseMonth','Purchase month'],['usefulLifeMonths','Useful life (months)']].map(([key,label])=><Field key={key} label={label} value={asset[key]??''} onChange={value=>setFixedAssets(fixedAssets.map((item,i)=>i===index?{...item,[key]:value}:item))}/>)}</div></div>)}<button className="add-row" onClick={()=>setFixedAssets([...fixedAssets,{id:`asset-${Date.now()}`,name:'',category:'Property and equipment',purchaseAmount:0,purchaseMonth:1,usefulLifeMonths:120}])}><Plus size={16}/>Add fixed asset</button></>}
        {active==='tax'&&<>{fieldGrid(tax,setTax,[['incomeTaxRate','Corporate income-tax rate','%'],['salesTaxRate','Sales-tax rate, where applicable','%'],['depreciation','Depreciation assumption'],['openingLosses','Opening losses','$'],['ownerDraws','Dividend or owner-draw assumptions','$ / month']])}</>}
        {active==='outputs'&&<FinancialOutputs projection={centralProjection}/>}
      </div>
      <div className="metrics finance-metrics"><Metric label="Year 1 revenue" value={formatMoney(years[0].revenue)} trend="Live forecast"/><Metric label="Year 1 gross margin" value={(years[0].revenue?years[0].grossProfit/years[0].revenue*100:0).toFixed(1)+'%'} trend="After direct costs"/><Metric label="Break-even" value={months.find(x=>x.ebitda>0)?.month?'Month '+months.find(x=>x.ebitda>0).month:'Not reached'} trend="Operating basis"/></div></section>
    </div>
  </div>;
}

function LoanDebtService({loans,setLoans,currency,onPrevious,onNext}) {
  const blank=()=>normalizeLoan({id:`loan-${Date.now()}`,loan_name:'',lender_name:null,loan_type:'term_loan',loan_status:'proposed',original_principal:0,opening_balance:0,annual_interest_rate:0,amortization_months:60,term_months:null,payment_frequency:'monthly',loan_start_month:1,first_payment_month:2,interest_only_months:0,interest_only_rate_override:null,financing_fee:0,financing_fee_treatment:'paid_upfront',balloon_payment:0,balloon_payment_month:null,notes:'',is_active:true});
  const [editing,setEditing]=useState(null); const [attempted,setAttempted]=useState(false); const [scheduleId,setScheduleId]=useState(null); const [saveStatus,setSaveStatus]=useState('Saved');
  const projection=useMemo(()=>calculateLoanProjection({loans,projectionMonths:36}),[loans]);
  const format=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:currency||'USD',minimumFractionDigits:0,maximumFractionDigits:2}).format(value||0);
  const errors=editing?validateLoan(editing,36):[]; const error=field=>attempted?errors.find(item=>item.field===field)?.message:null;
  const change=(key,value)=>setEditing(current=>({...current,[key]:value,...(key==='loan_status'?value==='existing'?{loan_start_month:1,first_payment_month:1,financing_fee:0}:{first_payment_month:Number(current.loan_start_month||1)+1}:{}),...(key==='loan_start_month'&&current.loan_status==='proposed'?{first_payment_month:Number(value)+1}:{})}));
  const commit=updater=>{setSaveStatus('Saving…');setLoans(updater);window.setTimeout(()=>setSaveStatus('Saved'),350)};
  const save=()=>{setAttempted(true);if(errors.length)return;const value=normalizeLoan(editing);commit(current=>current.some(item=>item.id===value.id)?current.map(item=>item.id===value.id?value:item):[...current,value]);setEditing(null)};
  const duplicate=item=>commit(current=>[...current,{...item,id:`loan-${Date.now()}`,loan_name:`${item.loan_name} Copy`,display_order:current.length+1}]);
  const remove=item=>{if(window.confirm(`Delete “${item.loan_name}”? This cannot be undone.`))commit(current=>current.filter(value=>value.id!==item.id))};
  const selected=projection.loan_schedules.find(item=>item.loan.id===scheduleId);
  const field=(key,label,props={})=><div className="field"><label htmlFor={`loan-${key}`}>{label}</label><input id={`loan-${key}`} {...props} value={editing[key]??''} aria-invalid={Boolean(error(key))} aria-describedby={error(key)?`loan-${key}-error`:undefined} onChange={event=>change(key,event.target.value)}/>{error(key)&&<small className="field-error" id={`loan-${key}-error`}>{error(key)}</small>}</div>;
  const select=(key,label,options)=><div className="field"><label htmlFor={`loan-${key}`}>{label}</label><select id={`loan-${key}`} value={editing[key]??''} onChange={event=>change(key,event.target.value)}>{options.map(([value,text])=><option value={value} key={value}>{text}</option>)}</select>{error(key)&&<small className="field-error">{error(key)}</small>}</div>;
  return <div className="loan-module">
    <div className="expense-page-heading"><div><h1>Loans &amp; Debt Service</h1><p>Enter existing and proposed business loans. Monthly debt payments, interest, principal, and outstanding balances will be calculated automatically.</p></div><span className={`save-state ${saveStatus==='Saved'?'is-saved':''}`}>{saveStatus==='Saved'&&<Check size={14}/>} {saveStatus}</span></div>
    <div className="expense-intro"><div><h3>Debt assumptions</h3><p>Loan proceeds and debt service use one-based projection months.</p></div><button className="primary" onClick={()=>{setAttempted(false);setEditing(blank())}}><Plus size={16}/>Add Loan</button></div>
    <div className="expense-table-wrap"><table className="expense-table loan-table"><thead><tr><th>Loan</th><th>Status</th><th>Principal / Opening</th><th>Rate</th><th>Amortization</th><th>Monthly Payment</th><th>Year 1</th><th>Year 2</th><th>Year 3</th><th>Ending Balance</th><th>Actions</th></tr></thead><tbody>{projection.loan_schedules.map(item=><tr key={item.loan.id}><td><strong>{item.loan.loan_name}</strong><small>{item.loan.lender_name||'No lender specified'}</small></td><td><span className="loan-status">{item.loan.loan_status}</span></td><td>{format(item.loan.loan_status==='existing'?item.loan.opening_balance:item.loan.original_principal)}</td><td>{item.loan.annual_interest_rate}%</td><td>{item.loan.amortization_months} mo.</td><td>{format(item.monthly_payment)}</td>{[0,1,2].map(year=><td key={year}>{format(summarizeLoanYear(item.monthly,year))}</td>)}<td>{format(item.monthly.at(-1)?.closing_balance)}</td><td><div className="expense-actions"><button title="Edit" aria-label={`Edit ${item.loan.loan_name}`} onClick={()=>{setAttempted(false);setEditing({...item.loan})}}><PencilLine size={15}/></button><button title="Duplicate" aria-label={`Duplicate ${item.loan.loan_name}`} onClick={()=>duplicate(item.loan)}><Copy size={15}/></button><button title="View schedule" aria-label={`View ${item.loan.loan_name} schedule`} onClick={()=>setScheduleId(item.loan.id)}><Table2 size={15}/></button><button title="Delete" aria-label={`Delete ${item.loan.loan_name}`} onClick={()=>remove(item.loan)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{!loans.length&&<div className="expense-empty"><CircleDollarSign size={27}/><h3>No loans have been added.</h3><p>Add proposed or existing business financing to calculate debt service.</p><button className="primary" onClick={()=>setEditing(blank())}><Plus size={16}/>Add First Loan</button></div>}</div>
    <section className="loan-summary loan-summary-wide"><div><span>Total proposed proceeds</span><strong>{format(projection.totals.total_proceeds)}</strong></div><div><span>Opening existing debt</span><strong>{format(loans.filter(x=>x.loan_status==='existing').reduce((n,x)=>n+Number(x.opening_balance),0))}</strong></div>{[0,1,2].map(year=><div key={year}><span>Year {year+1} debt service</span><strong>{format(projection.annual[year]?.debt_service)}</strong></div>)}<div><span>Total interest</span><strong>{format(projection.totals.total_interest)}</strong></div><div><span>Total principal repaid</span><strong>{format(projection.totals.total_principal)}</strong></div><div><span>Ending debt balance</span><strong>{format(projection.totals.ending_debt)}</strong></div></section>
    <div className="workflow-navigation"><button className="secondary" onClick={onPrevious}><ArrowLeft size={16}/>Previous: Payroll &amp; Staffing</button><button className="primary" onClick={onNext}>Save &amp; continue <ArrowRight size={16}/></button></div>
    {editing&&<div className="expense-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setEditing(null)}><section className="expense-modal loan-modal" role="dialog" aria-modal="true" aria-labelledby="loan-form-title"><div className="expense-modal-head"><div><span className="eyebrow">LOAN ASSUMPTION</span><h3 id="loan-form-title">{loans.some(item=>item.id===editing.id)?'Edit loan':'Add loan'}</h3><p>Fields marked with * are required.</p></div><button aria-label="Close loan form" onClick={()=>setEditing(null)}><X size={19}/></button></div><div className="expense-form-grid">
      {field('loan_name','Loan name *',{maxLength:120,placeholder:'e.g. Business term loan'})}{field('lender_name','Lender name',{maxLength:120,placeholder:'Optional'})}
      {select('loan_status','Loan status *',[['proposed','Proposed'],['existing','Existing']])}{select('loan_type','Loan type *',LOAN_TYPES.map(value=>[value,value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())]))}
      {editing.loan_status==='proposed'?field('original_principal','Original principal *',{type:'number',min:0,step:'.01'}):field('opening_balance','Opening balance *',{type:'number',min:0,step:'.01'})}
      {field('annual_interest_rate','Annual interest rate (%) *',{type:'number',min:0,max:100,step:'.001'})}{field('amortization_months',editing.loan_status==='existing'?'Remaining amortization (months) *':'Amortization period (months) *',{type:'number',min:1,max:600})}{field('term_months','Contractual term (months)',{type:'number',min:1})}
      {editing.loan_status==='proposed'&&field('loan_start_month','Loan start month *',{type:'number',min:1,max:36})}{field('first_payment_month','First payment month *',{type:'number',min:1,max:36,disabled:editing.loan_status==='existing'})}
      {field('interest_only_months','Interest-only months',{type:'number',min:0,max:599})}{field('interest_only_rate_override','Interest-only rate override (%)',{type:'number',min:0,max:100,step:'.001'})}
      {editing.loan_status==='proposed'&&field('financing_fee','Financing fee',{type:'number',min:0,step:'.01'})}{editing.loan_status==='proposed'&&select('financing_fee_treatment','Fee treatment',[['paid_upfront','Paid upfront'],['deducted_from_proceeds','Deducted from proceeds']])}
      {field('balloon_payment','Balloon payment',{type:'number',min:0,step:'.01'})}{Number(editing.balloon_payment)>0&&field('balloon_payment_month','Balloon payment month *',{type:'number',min:1})}
      <div className="field wide"><label htmlFor="loan-notes">Notes</label><textarea id="loan-notes" rows="3" value={editing.notes} onChange={event=>change('notes',event.target.value)}/></div>
      </div>{attempted&&errors.length>0&&<div className="form-errors" role="alert"><AlertTriangle size={16}/>Review the highlighted loan assumptions.</div>}<div className="expense-modal-actions"><button className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" onClick={save}>Save Loan</button></div></section></div>}
    {selected&&<div className="expense-modal-backdrop"><section className="expense-modal schedule-modal" role="dialog" aria-modal="true" aria-labelledby="schedule-title"><div className="expense-modal-head"><div><span className="eyebrow">AMORTIZATION SCHEDULE</span><h3 id="schedule-title">{selected.loan.loan_name}</h3><p>36-month projection preview</p></div><button aria-label="Close schedule" onClick={()=>setScheduleId(null)}><X size={19}/></button></div><div className="schedule-scroll"><table className="expense-table"><thead><tr><th>Month</th><th>Opening</th><th>Proceeds</th><th>Payment</th><th>Interest</th><th>Principal</th><th>Fee</th><th>Balloon</th><th>Closing</th></tr></thead><tbody>{selected.monthly.map(row=><tr key={row.month_index}><td>{row.month_index}</td><td>{format(row.opening_balance)}</td><td>{format(row.loan_proceeds)}</td><td>{format(row.scheduled_payment)}</td><td>{format(row.interest_payment)}</td><td>{format(row.principal_payment)}</td><td>{format(row.financing_fee)}</td><td>{format(row.balloon_payment)}</td><td>{format(row.closing_balance)}</td></tr>)}</tbody></table></div></section></div>}
  </div>;
}
const summarizeLoanYear=(rows,year)=>rows.slice(year*12,year*12+12).reduce((sum,row)=>sum+row.scheduled_payment+row.balloon_payment,0);

function OperatingExpenses({expenses,setExpenses,projection,revenueMonthly,revenueStreams,onPrevious,onNext}) {
  const projectionStart=new Date(2026,7,1);
  const monthOptions=Array.from({length:36},(_,index)=>({value:String(index+1),label:new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(new Date(projectionStart.getFullYear(),projectionStart.getMonth()+index,1))}));
  const emptyExpense=()=>({id:`expense-${Date.now()}`,name:'',category:'',amount:'',annualAmounts:['','',''],calculationType:'Fixed Amount',frequency:'Monthly',startMonth:1,endMonth:null,annualIncrease:0,revenueBasis:'total_revenue',revenueStreamIds:[],notes:''});
  const [editing,setEditing]=useState(null);
  const [attempted,setAttempted]=useState(false);
  const [saveStatus,setSaveStatus]=useState('Saved');
  const openNew=()=>{setAttempted(false);setEditing(emptyExpense())};
  const openEdit=expense=>{setAttempted(false);setEditing({...normalizeOperatingExpense(expense)})};
  const errors=editing?validateOperatingExpense(editing):[];
  const change=(key,value)=>setEditing(current=>({...current,[key]:value}));
  const changeType=value=>setEditing(current=>({...current,calculationType:value,frequency:value==='Percentage of Revenue'?'Monthly':current.frequency||'Monthly',amount:''}));
  const commit=updater=>{setSaveStatus('Saving…');setExpenses(updater);window.setTimeout(()=>setSaveStatus('Saved'),500)};
  const saveExpense=()=>{setAttempted(true);if(errors.length)return;const saved=normalizeOperatingExpense(editing);commit(current=>current.some(item=>item.id===saved.id)?current.map(item=>item.id===saved.id?saved:item):[...current,saved]);setEditing(null)};
  const removeExpense=id=>commit(current=>current.filter(item=>item.id!==id));
  const duplicateExpense=expense=>commit(current=>[...current,{...expense,id:`expense-${Date.now()}`,name:`${expense.name} (Copy)`}]);
  const totals=[0,1,2].map(year=>projection.monthly.slice(year*12,year*12+12).reduce((sum,value)=>sum+value,0));
  const fixedTotal=projection.totalFixedExpenses;
  const monthLabel=value=>monthOptions[Number(value)-1]?.label||'Projection end';
  return <div className="operating-expenses">
    <div className="expense-page-heading"><div><h1>Operating Expenses</h1><p>Enter the recurring, scheduled, and revenue-based expenses required to operate the business. Payroll and loan payments will be added separately.</p></div><span className={`save-state ${saveStatus==='Saved'?'is-saved':''}`}>{saveStatus==='Saved'&&<Check size={14}/>} {saveStatus}</span></div>
    <div className="expense-intro"><div><h3>Expense schedule</h3><p>Amounts flow into your 36-month forecast based on each expense’s calculation, frequency, and active period.</p></div><button className="primary" onClick={openNew}><Plus size={16}/>Add Operating Expense</button></div>
    <div className="expense-table-wrap"><table className="expense-table expense-table-detailed"><thead><tr><th>Expense</th><th>Category</th><th>Calculation</th><th>Frequency</th><th>Start</th><th>End</th><th>Month 1</th><th>Year 1</th><th>Year 2</th><th>Year 3</th><th>Actions</th></tr></thead><tbody>{expenses.map(expense=>{const normalized=normalizeOperatingExpense(expense);const item=calculateOperatingExpenses([normalized],36,revenueMonthly,revenueStreams);return <tr key={expense.id}><td><strong>{normalized.name}</strong>{normalized.notes&&<small>{normalized.notes}</small>}</td><td>{expenseCategoryLabel(normalized.category)}</td><td>{normalized.calculationType==='Percentage of Revenue'?`${normalized.amount}% of revenue`:`${money(normalized.amount)} fixed`}</td><td>{normalized.calculationType==='Percentage of Revenue'?'Monthly':normalized.frequency}</td><td>{monthLabel(normalized.startMonth)}</td><td>{normalized.endMonth?monthLabel(normalized.endMonth):'Projection end'}</td><td>{money(item.monthly[0]||0)}</td>{[0,1,2].map(year=><td key={year}>{money(item.monthly.slice(year*12,year*12+12).reduce((a,b)=>a+b,0))}</td>)}<td><div className="expense-actions"><button title="Edit" onClick={()=>openEdit(expense)}><PencilLine size={15}/></button><button title="Duplicate" onClick={()=>duplicateExpense(expense)}><Copy size={15}/></button><button title="Delete" onClick={()=>removeExpense(expense.id)}><Trash2 size={15}/></button></div></td></tr>})}</tbody></table>{!expenses.length&&<div className="expense-empty"><CircleDollarSign size={27}/><h3>No operating expenses have been added.</h3><p>Add rent, insurance, software, marketing, utilities, or professional fees.</p><button className="primary" onClick={openNew}><Plus size={16}/>Add First Expense</button></div>}</div>
    <section className="expense-summary">{totals.map((total,index)=><div key={index}><span>Year {index+1} operating expenses</span><strong>{money(total)}</strong></div>)}<div><span>Fixed expenses total</span><strong>{money(fixedTotal)}</strong></div><div><span>Revenue-based expenses total</span><strong>{money(projection.totalRevenueBasedExpenses)}</strong></div><div><span>Number of active expenses</span><strong>{expenses.length}</strong></div></section>
    <section className="monthly-preview"><div><strong>Monthly preview</strong><span>First 12 months</span></div><div className="month-strip">{projection.monthly.slice(0,12).map((value,index)=><div key={index}><span>{monthOptions[index].label.split(' ')[0].slice(0,3)}</span><b>{money(value)}</b></div>)}</div></section>
    <div className="workflow-navigation"><button className="secondary" onClick={onPrevious}><ArrowLeft size={16}/>Previous: Startup Costs</button><button className="primary" onClick={onNext}>Next: Payroll & Staffing <ArrowRight size={16}/></button></div>
    {editing&&<div className="expense-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setEditing(null)}><section className="expense-modal" role="dialog" aria-modal="true" aria-labelledby="expense-form-title"><div className="expense-modal-head"><div><span className="eyebrow">OPERATING EXPENSE</span><h3 id="expense-form-title">{expenses.some(item=>item.id===editing.id)?'Edit expense':'Add an expense'}</h3><p>Fields marked with * are required.</p></div><button aria-label="Close expense form" onClick={()=>setEditing(null)}><X size={19}/></button></div>
      <div className="expense-form-grid">
        <div className="field"><label>Expense name *</label><input maxLength="120" value={editing.name} placeholder="e.g. Rent or insurance" onChange={e=>change('name',e.target.value)}/></div><Select label="Expense category *" value={editing.category} options={[{value:'',label:'Select a category'},...EXPENSE_CATEGORIES]} onChange={value=>change('category',value)}/>
        <fieldset className="expense-type wide"><legend>Calculation type *</legend>{['Fixed Amount','Percentage of Revenue'].map(type=><button type="button" key={type} className={editing.calculationType===type?'active':''} onClick={()=>changeType(type)}>{type}</button>)}</fieldset>
        <div className="field"><label>{editing.calculationType==='Percentage of Revenue'?'Percentage rate (%) *':'Year 1 amount *'}</label><input type="number" min="0" max={editing.calculationType==='Percentage of Revenue'?100:undefined} step="0.01" value={editing.amount} onChange={e=>{change('amount',e.target.value);if(editing.calculationType==='Fixed Amount')change('annualAmounts',[e.target.value,editing.annualAmounts?.[1]??'',editing.annualAmounts?.[2]??''])}}/></div>
        {editing.calculationType==='Fixed Amount'&&<><div className="field"><label>Year 2 amount</label><input type="number" min="0" step="0.01" value={editing.annualAmounts?.[1]??''} placeholder="Same as Year 1" onChange={e=>change('annualAmounts',[editing.annualAmounts?.[0]??editing.amount,e.target.value,editing.annualAmounts?.[2]??''])}/></div><div className="field"><label>Year 3 amount</label><input type="number" min="0" step="0.01" value={editing.annualAmounts?.[2]??''} placeholder="Same as Year 2" onChange={e=>change('annualAmounts',[editing.annualAmounts?.[0]??editing.amount,editing.annualAmounts?.[1]??'',e.target.value])}/><small>Amounts use the selected frequency in each projection year.</small></div></>}
        {editing.calculationType==='Percentage of Revenue'?<><Select label="Revenue basis *" value={editing.revenueBasis} options={[{value:'total_revenue',label:'Total Revenue'},{value:'selected_revenue_streams',label:'Selected Revenue Streams'}]} onChange={value=>change('revenueBasis',value)}/>{editing.revenueBasis==='selected_revenue_streams'&&<fieldset className="stream-selector wide"><legend>Revenue streams *</legend>{revenueStreams.map(stream=><label key={stream.id}><input type="checkbox" checked={editing.revenueStreamIds.includes(stream.id)} onChange={e=>change('revenueStreamIds',e.target.checked?[...editing.revenueStreamIds,stream.id]:editing.revenueStreamIds.filter(id=>id!==stream.id))}/>{stream.name}</label>)}</fieldset>}</>:<Select label="Frequency *" value={editing.frequency} options={['Monthly','Quarterly','Semi-Annual','Annual','One-Time']} onChange={value=>change('frequency',value)}/>}
        <Select label="Start month *" value={String(editing.startMonth)} options={monthOptions} onChange={value=>change('startMonth',Number(value))}/><Select label="End month" value={editing.endMonth===null?'':String(editing.endMonth)} options={[{value:'',label:'Continue through projection period'},...monthOptions]} onChange={value=>change('endMonth',value?Number(value):null)}/>
        <div className="field"><label>Annual increase percentage</label><input type="number" min="0" step="0.01" value={editing.annualIncrease} onChange={e=>change('annualIncrease',e.target.value)}/><small>Applied at the start of each new projection year.</small></div>
        {editing.calculationType==='Fixed Amount'&&editing.frequency!=='Monthly'&&<div className="payment-timing"><strong>Payment timing</strong><span>{editing.frequency==='One-Time'?'Paid only in the selected start month.':`First payment in the selected start month, then every ${editing.frequency==='Quarterly'?'three':editing.frequency==='Semi-Annual'?'six':'twelve'} months.`}</span></div>}
        <div className="field wide"><label>Notes</label><textarea value={editing.notes} placeholder="Vendor or assumption (optional)" onChange={e=>change('notes',e.target.value)}/></div>
      </div>{attempted&&errors.length>0&&<div className="expense-errors" role="alert">{errors.map(error=><span key={`${error.field}-${error.message}`}>{error.message}</span>)}</div>}<div className="expense-modal-actions"><button className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" onClick={saveExpense}>Save expense</button></div>
    </section></div>}
  </div>;
}
function PayrollStaffing({positions,setPositions,projection,onPrevious,onNext,currency='USD'}) {
  const monthOptions=Array.from({length:36},(_,i)=>({value:String(i+1),label:`Month ${i+1}`}));
  const blank=()=>normalizeStaffingPosition({id:`staff-${Date.now()}`,position_title:'',department:null,worker_type:'employee',compensation_type:'hourly',number_of_workers:1,hourly_rate:20,weekly_hours:40,annual_salary:null,monthly_contractor_amount:null,monthly_hours:null,employer_cost_percentage:0,monthly_benefits_per_worker:0,annual_bonus_per_worker:0,bonus_month:12,start_month:1,end_month:null,annual_compensation_increase_percentage:0,notes:''});
  const [editing,setEditing]=useState(null),[attempted,setAttempted]=useState(false),[saveStatus,setSaveStatus]=useState('Saved');
  const cash=value=>new Intl.NumberFormat('en-US',{style:'currency',currency,minimumFractionDigits:2,maximumFractionDigits:2}).format(value||0);
  const errors=editing?validateStaffingPosition(editing):[];
  const change=(key,value)=>setEditing(current=>({...current,[key]:value}));
  const commit=updater=>{setSaveStatus('Saving…');setPositions(updater);window.setTimeout(()=>setSaveStatus('Saved'),350)};
  const save=()=>{setAttempted(true);if(errors.length)return;const item=normalizeStaffingPosition(editing);commit(current=>current.some(p=>p.id===item.id)?current.map(p=>p.id===item.id?item:p):[...current,item]);setEditing(null)};
  const remove=item=>{if(window.confirm(`Delete ${item.position_title}? This cannot be undone.`))commit(current=>current.filter(p=>p.id!==item.id))};
  const duplicate=item=>commit(current=>[...current,{...item,id:`staff-${Date.now()}`,position_title:`${item.position_title} Copy`}]);
  const result=id=>projection.position_results.find(row=>row.position.id===id);
  const workerHelp={employee:'An employee receiving wages or salary through the business.',owner:'An owner receiving compensation from the business.',contractor:'An independent worker or external service provider paid directly by the business.'};
  return <div className="payroll-staffing">
    <div className="expense-page-heading"><div><h1>Payroll &amp; Staffing</h1><p>Enter employees, owner compensation, and contractors expected during the projection period.</p></div><span className={`save-state ${saveStatus==='Saved'?'is-saved':''}`}>{saveStatus==='Saved'&&<Check size={14}/>} {saveStatus}</span></div>
    <div className="expense-intro"><div><h3>Staffing assumptions</h3><p>Payroll costs are stored separately from operating expenses and included automatically in projections.</p></div><button className="primary" onClick={()=>{setAttempted(false);setEditing(blank())}}><Plus size={16}/>Add Position</button></div>
    <div className="direct-cost-warning"><AlertTriangle size={16}/><span>Ensure this staffing cost is not already included in direct costs.</span></div>
    <div className="expense-table-wrap"><table className="expense-table payroll-table"><thead><tr><th>Position</th><th>Worker Type</th><th>Compensation</th><th>Workers</th><th>Start</th><th>End</th><th>Year 1 Cost</th><th>Year 2 Cost</th><th>Year 3 Cost</th><th>Actions</th></tr></thead><tbody>{positions.map(item=>{const row=result(item.id);return <tr key={item.id}><td><strong>{item.position_title}</strong><small>{item.department?.replaceAll('_',' ')||'No department'}</small></td><td>{item.worker_type}</td><td>{item.compensation_type.replaceAll('_',' ')}</td><td>{item.number_of_workers}</td><td>Month {item.start_month}</td><td>{item.end_month?`Month ${item.end_month}`:'Projection end'}</td>{[0,1,2].map(y=><td key={y}>{cash(row?.annual_totals[y])}</td>)}<td><div className="expense-actions"><button aria-label={`Edit ${item.position_title}`} onClick={()=>{setAttempted(false);setEditing({...item})}}><PencilLine size={15}/></button><button aria-label={`Duplicate ${item.position_title}`} onClick={()=>duplicate(item)}><Copy size={15}/></button><button aria-label={`Delete ${item.position_title}`} onClick={()=>remove(item)}><Trash2 size={15}/></button></div></td></tr>})}</tbody></table>{!positions.length&&<div className="expense-empty"><Users size={27}/><h3>No staffing positions have been added.</h3><p>Add employees, owner compensation, or contract workers expected during the projection period.</p><button className="primary" onClick={()=>setEditing(blank())}><Plus size={16}/>Add First Position</button></div>}</div>
    <section className="payroll-summary">{projection.annual_summaries.slice(0,3).map(row=><article key={row.year}><span>YEAR {row.year}</span><strong>{cash(row.total_staffing_cost)}</strong><dl><div><dt>Base employee compensation</dt><dd>{cash(row.base_employee_compensation)}</dd></div><div><dt>Owner compensation</dt><dd>{cash(row.owner_compensation)}</dd></div><div><dt>Employer payroll costs</dt><dd>{cash(row.employer_costs)}</dd></div><div><dt>Benefits</dt><dd>{cash(row.benefits)}</dd></div><div><dt>Bonuses</dt><dd>{cash(row.bonuses)}</dd></div><div><dt>Contractors</dt><dd>{cash(row.contractor_costs)}</dd></div><div><dt>Year-end people</dt><dd>{row.ending_headcount}</dd></div></dl></article>)}</section>
    <div className="workflow-navigation"><button className="secondary" onClick={onPrevious}><ArrowLeft size={16}/>Previous: Operating Expenses</button><button className="primary" onClick={onNext}>Next step <ArrowRight size={16}/></button></div>
    {editing&&<div className="expense-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><section className="expense-modal" role="dialog" aria-modal="true" aria-labelledby="staffing-form-title"><div className="expense-modal-head"><div><span className="eyebrow">STAFFING POSITION</span><h3 id="staffing-form-title">{positions.some(p=>p.id===editing.id)?'Edit position':'Add position'}</h3><p>Fields marked with * are required.</p></div><button aria-label="Close position form" onClick={()=>setEditing(null)}><X size={19}/></button></div><div className="expense-form-grid">
      <div className="field"><label>Position title *</label><input value={editing.position_title} maxLength="120" onChange={e=>change('position_title',e.target.value)}/></div>
      <Select label="Department" value={editing.department||''} options={[{value:'',label:'No department'},...DEPARTMENTS.map(value=>({value,label:value.replaceAll('_',' ')}))]} onChange={v=>change('department',v||null)}/>
      <Select label="Worker type *" value={editing.worker_type} options={['employee','owner','contractor']} onChange={v=>setEditing(current=>normalizeStaffingPosition({...current,worker_type:v,compensation_type:v==='contractor'?(current.compensation_type==='hourly'?'hourly':'fixed_monthly'):current.compensation_type==='fixed_monthly'?'salaried':current.compensation_type}))}/>
      <Select label="Compensation type *" value={editing.compensation_type} options={editing.worker_type==='contractor'?['hourly','fixed_monthly']:['hourly','salaried','fixed_monthly','unpaid']} onChange={v=>change('compensation_type',v)}/>
      <div className="field wide helper"><small>{workerHelp[editing.worker_type]}</small></div>
      <div className="field"><label>Number of workers *</label><input type="number" min="1" max="100000" step="1" value={editing.number_of_workers} onChange={e=>change('number_of_workers',e.target.value)}/></div>
      {editing.compensation_type==='hourly'&&<><div className="field"><label>Hourly rate *</label><input type="number" min="0" step="0.01" value={editing.hourly_rate??''} onChange={e=>change('hourly_rate',e.target.value)}/></div><div className="field"><label>{editing.worker_type==='contractor'?'Monthly hours *':'Weekly hours *'}</label><input type="number" min="0.01" max={editing.worker_type==='contractor'?undefined:168} step="0.01" value={(editing.worker_type==='contractor'?editing.monthly_hours:editing.weekly_hours)??''} onChange={e=>change(editing.worker_type==='contractor'?'monthly_hours':'weekly_hours',e.target.value)}/></div></>}
      {editing.compensation_type==='salaried'&&<div className="field"><label>Annual salary *</label><input type="number" min="0" step="0.01" value={editing.annual_salary??''} onChange={e=>change('annual_salary',e.target.value)}/></div>}
      {editing.compensation_type==='fixed_monthly'&&<div className="field"><label>Fixed monthly amount *</label><input type="number" min="0" step="0.01" value={editing.monthly_contractor_amount??''} onChange={e=>change('monthly_contractor_amount',e.target.value)}/></div>}
      {editing.worker_type!=='contractor'&&<><div className="field"><label>Employer cost percentage</label><input type="number" min="0" max="100" step="0.01" value={editing.employer_cost_percentage} onChange={e=>change('employer_cost_percentage',e.target.value)}/><small>Additional employer payroll costs calculated as a percentage of base compensation.</small></div><div className="field"><label>Monthly benefits per worker</label><input type="number" min="0" step="0.01" value={editing.monthly_benefits_per_worker} onChange={e=>change('monthly_benefits_per_worker',e.target.value)}/></div><div className="field"><label>Annual bonus per worker</label><input type="number" min="0" step="0.01" value={editing.annual_bonus_per_worker} onChange={e=>change('annual_bonus_per_worker',e.target.value)}/></div>{Number(editing.annual_bonus_per_worker)>0&&<Select label="Bonus month *" value={String(editing.bonus_month||'')} options={monthOptions.slice(0,12)} onChange={v=>change('bonus_month',Number(v))}/>}</>}
      <Select label="Start month *" value={String(editing.start_month)} options={monthOptions.map((option,index)=>({...option,label:`${option.label} · Year ${Math.floor(index/12)+1}`}))} onChange={v=>change('start_month',Number(v))}/><Select label="End month" value={editing.end_month?String(editing.end_month):''} options={[{value:'',label:'Continue through projection'},...monthOptions]} onChange={v=>change('end_month',v?Number(v):null)}/><div className="field wide helper"><small>To add someone in Year 2 or Year 3, select Month 13 or Month 25 as their start month. Their payroll and headcount begin automatically in that year.</small></div>
      <div className="field"><label>Annual compensation increase</label><input type="number" min="0" max="100" step="0.01" value={editing.annual_compensation_increase_percentage} onChange={e=>change('annual_compensation_increase_percentage',e.target.value)}/><small>Applied to wages or salary at the start of each new projection year.</small></div><div className="field wide"><label>Notes</label><textarea maxLength="2000" value={editing.notes} onChange={e=>change('notes',e.target.value)}/></div>
    </div>{attempted&&errors.length>0&&<div className="expense-errors" role="alert">{errors.map(e=><span key={`${e.field}-${e.message}`}>{e.message}</span>)}</div>}<div className="expense-modal-actions"><button className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" onClick={save}>Save position</button></div></section></div>}
  </div>;
}

function FinancialTotal({label,value}){return <div className="financial-total"><span>{label}</span><strong>{money(value)}</strong></div>}

function FinancialOutputs({projection}) {
  const [showRisks,setShowRisks]=useState(true);
  const [showWarnings,setShowWarnings]=useState(true);
  const analysis=useMemo(()=>calculateFinancialAnalysis(projection),[projection]);
  const monthly=projection.monthly;
  if(projection.validation.errors.length)return <div className="financial-empty projection-error" role="alert"><AlertTriangle/><h3>Financial projections could not be calculated because some assumptions are incomplete.</h3><ul>{projection.validation.errors.map(error=><li key={`${error.code}-${error.monthIndex||''}`}>{error.message}{error.monthIndex?` (Month ${error.monthIndex})`:''}</li>)}</ul></div>;
  if(!monthly.length||!projection.statements.annual.length)return <div className="financial-empty"><BarChart3/><h3>No financial results yet</h3><p>Add revenue and expense assumptions to create your financial summary.</p></div>;
  const dscr=analysis.annualMetrics[0]?.dscr||{value:null};
  return <div className="results-dashboard">
    <FinancialStatementsView projection={projection}/>
    <FinancialAnalysisView analysis={analysis} currency={projection.currency}/>
    <section className="optional-review" aria-label="Review Financial Risks"><div className="optional-review-heading"><div><span className="eyebrow">5 · REVIEW FINANCIAL RISKS</span><h3>Review Financial Risks</h3></div><button type="button" className="secondary" aria-expanded={showRisks} onClick={()=>setShowRisks(value=>!value)}>{showRisks?'Hide':'Show'}</button></div>{showRisks&&<div className="results-warning" role="status"><AlertTriangle/><div><strong>{analysis.cashAnalysis.minimumCash<0||dscr.value!=null&&dscr.value<1?'Risks need attention':'No critical financial risks identified'}</strong><span>{analysis.cashAnalysis.minimumCash<0?'Cash falls below zero during the forecast. ':''}{dscr.value!=null&&dscr.value<1?'Year 1 EBITDA does not fully cover scheduled debt service.':''}</span></div></div>}</section>
    <section className="optional-review" aria-label="Calculation warnings"><div className="optional-review-heading"><div><span className="eyebrow">6 · CALCULATION WARNINGS</span><h3>Calculation warnings</h3></div><button type="button" className="secondary" aria-expanded={showWarnings} onClick={()=>setShowWarnings(value=>!value)}>{showWarnings?'Hide':'Show'}</button></div>{showWarnings&&(projection.validation.warnings.length>0?<div className="results-warning" role="status"><AlertTriangle/><div><strong>Review calculation warnings</strong><span>{projection.validation.warnings.map(item=>item.message).join(' ')}</span></div></div>:<p className="statement-source">No calculation warnings.</p>)}</section>
  </div>;
}
function FinancialAnalysisView({analysis,currency}){
  const cash=analysis.cashAnalysis,debt=analysis.debtAnalysis,y1=analysis.annualMetrics[0];
  const cashFormat=value=>new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(value||0);
  const pct=value=>value==null?'Not applicable':`${(value*100).toFixed(1)}%`; const ratio=value=>value==null?'Not applicable':`${value.toFixed(2)}x`;
  const rows=[['Revenue','revenue',cashFormat],['Revenue Growth','revenueGrowth',value=>pct(value.value)],['Gross Profit','grossProfit',cashFormat],['Gross Margin','grossMargin',pct],['EBITDA','ebitda',cashFormat],['EBITDA Margin','ebitdaMargin',pct],['Net Income','netIncome',cashFormat],['Net Margin','netMargin',pct],['Debt Service','debtService',cashFormat],['DSCR','dscr',value=>ratio(value.value)],['Current Ratio','currentRatio',value=>ratio(value.value)],['Working Capital','workingCapital',cashFormat],['Ending Cash','endingCash',cashFormat],['Ending Debt','endingDebt',cashFormat]];
  const cards=[['Revenue',cashFormat(y1?.revenue)],['Gross Margin',pct(y1?.grossMargin)],['EBITDA',cashFormat(y1?.ebitda)],['EBITDA Margin',pct(y1?.ebitdaMargin)],['Net Income',cashFormat(y1?.netIncome)],['DSCR',ratio(y1?.dscr.value)],['Working Capital',cashFormat(y1?.workingCapital)],['Ending Cash',cashFormat(y1?.endingCash)]];
  return <section className="financial-analysis-page" aria-label="Financial Analysis"><div className="statement-heading"><div><span className="eyebrow">4 · FINANCIAL ANALYSIS</span><h3>Deterministic Financial Analysis</h3><p>Read-only ratios, cash diagnostics, and rule-based warnings. Analysis version {analysis.metadata.analysisVersion}.</p></div></div>
    <div className="result-cards">{cards.map(([label,value])=><div className="result-card" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <section><h3 className="output-heading">Three-year analysis</h3><div className="results-table-wrap"><table className="results-table"><thead><tr><th>Metric</th>{analysis.annualMetrics.map(year=><th key={year.year}>Year {year.year}</th>)}</tr></thead><tbody>{rows.map(([label,key,format])=><tr key={key}><th>{label}</th>{analysis.annualMetrics.map(year=><td key={year.year}>{format(year[key])}</td>)}</tr>)}</tbody></table></div></section>
    <div className="analysis-columns"><section><h3>Cash &amp; Funding</h3><dl>{[['Opening Cash',cash.openingCash],['Minimum Cash',cash.minimumCash],['Month of Minimum Cash',cash.minimumCashMonth?.label||'Not applicable'],['First Negative Cash Month',cash.firstNegativeCashMonth?.label||'Not applicable'],['Maximum Projected Cash Shortfall',cash.maximumFundingShortfall],...cash.yearEndCash.map((value,index)=>[`Year ${index+1} Ending Cash`,value])].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{typeof value==='number'?cashFormat(value):value}</dd></div>)}</dl></section><section><h3>Debt Analysis</h3><dl>{[['Total Proposed Loan Funding',debt.totalProposedLoanFunding],['Opening Existing Debt',debt.openingExistingDebt],['Year 1 Debt Service',y1?.debtService||0],['Year 1 DSCR',ratio(y1?.dscr.value)],['Total Principal Repaid',debt.totalPrincipalRepaid],['Total Interest Paid',debt.totalInterestPaid],...debt.endingDebt.map((value,index)=>[`Year ${index+1} Ending Debt`,value])].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{typeof value==='number'?cashFormat(value):value}</dd></div>)}</dl></section></div>
    <section><h3>Financial Warnings</h3>{['error','warning','advisory'].map(severity=><div className={`warning-group ${severity}`} key={severity}><h4>{severity==='error'?'Errors':severity==='warning'?'Warnings':'Advisories'}</h4>{analysis.warnings.filter(item=>item.severity===severity).map(item=><article key={`${item.code}-${item.affectedPeriod||''}`}><strong>{item.title}</strong><p>{item.message}</p><small>{item.affectedPeriod?`${item.affectedPeriod} · `:''}{item.reviewArea}</small></article>)}{!analysis.warnings.some(item=>item.severity===severity)&&<p className="statement-source">None</p>}</div>)}</section>
  </section>;
}
const statementLineItems={
  income:[['REVENUE','','section'],['Total Revenue','revenue','total'],['Cost of Sales / Cost of Goods Sold','costOfSales'],['Gross Profit','grossProfit','total'],['OPERATING EXPENSES','','section'],['Payroll & Staffing','payroll','line-item'],['Total Operating Expenses','totalOperatingExpenses','total'],['EBITDA','ebitda','key-profit'],['Depreciation & Amortization','depreciationAndAmortization'],['EBIT / Operating Income','ebit','key-profit'],['Interest Expense','interestExpense'],['Earnings Before Tax','incomeBeforeTax','key-profit'],['Income Tax','incomeTax'],['Net Income','netIncome','grand']],
  cashflow:[['CASH FLOW FROM OPERATING ACTIVITIES','','section'],['Net Income','netIncome'],['Add: Depreciation & Amortization','depreciationAndAmortization'],['Change in Accounts Receivable','changeInAccountsReceivable'],['Change in Inventory','changeInInventory'],['Change in Accounts Payable','changeInAccountsPayable'],['Other Operating Adjustments','otherOperatingAdjustments'],['Net Cash from Operating Activities','cashFlowFromOperatingActivities','total'],['CASH FLOW FROM INVESTING ACTIVITIES','','section'],['Capital Expenditures','capitalExpenditures'],['Other Investing Activities','otherInvestingActivities'],['Net Cash from Investing Activities','cashFlowFromInvestingActivities','total'],['CASH FLOW FROM FINANCING ACTIVITIES','','section'],['Owner Contributions','ownerContributions'],['Loan Proceeds','loanProceeds'],['Loan Principal Repayments','loanPrincipalRepayments'],['Grant / Government Funding','otherFinancingActivities'],['Net Cash from Financing Activities','cashFlowFromFinancingActivities','total'],['NET CHANGE IN CASH','netChangeInCash','grand'],['Opening Cash','openingCash'],['Closing Cash','closingCash','grand']],
  balance:[['ASSETS','','section'],['Cash','cash'],['Accounts Receivable','accountsReceivable'],['Inventory','inventory'],['Other Current Assets','otherCurrentAssets'],['Total Current Assets','totalCurrentAssets','total'],['Gross Fixed Assets','grossFixedAssets'],['Less: Accumulated Depreciation','accumulatedDepreciation'],['Net Fixed Assets','netFixedAssets','total'],['Deposits / Other Assets','otherAssets'],['TOTAL ASSETS','totalAssets','grand'],['LIABILITIES','','section'],['Accounts Payable','accountsPayable'],['Current Portion of Debt','currentPortionOfDebt'],['Other Current Liabilities','otherCurrentLiabilities'],['Total Current Liabilities','totalCurrentLiabilities','total'],['Long-Term Debt','longTermDebt'],['TOTAL LIABILITIES','totalLiabilities','grand'],['EQUITY','','section'],['Owner Contributions','ownerContributions'],['Retained Earnings','retainedEarnings'],['Other Equity','otherEquity'],['TOTAL EQUITY','totalEquity','grand'],['TOTAL LIABILITIES & EQUITY','totalLiabilitiesAndEquity','grand'],['Balance Difference','balanceDifference','check']]
};
function FinancialStatementSection({projection,statement,title,number}){
  const [view,setView]=useState('annual');const [year,setYear]=useState(1);
  const annualPeriods=projection.statements.annual.slice(0,3);const periods=view==='annual'?(statement==='balance'?[projection.statements.opening,...annualPeriods]:annualPeriods):projection.statements.monthly.slice((year-1)*12,year*12);
  const detailRows=useMemo(()=>statement==='income'?incomeStatementDetailRows(projection.monthly):null,[projection,statement]);
  const baseRows=statementLineItems[statement];const rows=statement==='income'?baseRows.flatMap(row=>row[0]==='REVENUE'?[row,...detailRows.revenue]:row[2]==='section'&&row[0]==='OPERATING EXPENSES'?[row,...detailRows.recurringExpenses]:row[1]==='totalOperatingExpenses'?[...detailRows.startupExpenses,row]:[row]):baseRows;const key=statement==='income'?'incomeStatement':statement==='cashflow'?'cashFlowStatement':'balanceSheet';
  const format=value=>{if(Math.abs(value)<.005)return '—';const absolute=new Intl.NumberFormat('en-US',{style:'currency',currency:projection.currency,maximumFractionDigits:0}).format(Math.abs(value));return value<0?`(${absolute})`:absolute};
  const detailValue=(line,periodIndex)=>{const months=view==='annual'?projection.monthly.slice(periodIndex*12,periodIndex*12+12):[projection.monthly[(year-1)*12+periodIndex]];const [type,id]=line.split(':');return months.reduce((sum,month)=>sum+(type==='revenue'?(month?.revenueByStream.find(row=>row.id===id)?.revenue||0):type==='startup'?(month?.expensedStartupCostsByLine.find(row=>row.id===id)?.amount||0):(month?.operatingExpensesByLine.find(row=>row.id===id)?.amount||0)),0)};
  const issues=projection.statements.validation.errors;
  return <section className="financial-statements" aria-label={title}><div className="statement-heading"><div><span className="eyebrow">{number} · FINANCIAL STATEMENT</span><h3>{title}</h3><p>All amounts in {projection.currency}. {statement==='balance'?'Year 0 shows the opening, pre-operation position. ':''}Read-only results from model {projection.metadata.calculationVersion}.</p></div><div className="statement-controls"><div role="group" aria-label={`${title} period`}>{['annual','monthly'].map(id=><button type="button" key={id} aria-pressed={view===id} className={view===id?'active':''} onClick={()=>setView(id)}>{id==='annual'?'Annual':'Monthly'}</button>)}</div>{view==='monthly'&&<select aria-label={`${title} projection year`} value={year} onChange={event=>setYear(Number(event.target.value))}>{[1,2,3].map(value=><option key={value} value={value}>Projection Year {value}</option>)}</select>}</div></div>
    {issues.length>0&&<div className="statement-errors" role="alert"><AlertTriangle size={17}/><div><strong>Statement reconciliation errors</strong>{issues.map((issue,index)=><span key={`${issue.code}-${issue.monthIndex||index}`}>{issue.message}</span>)}</div></div>}
    <div className="results-table-wrap"><table className="results-table statement-table"><thead><tr><th>Description</th>{periods.map(period=><th key={period.label}>{view==='monthly'?new Date(`${period.date}T00:00:00Z`).toLocaleDateString('en-US',{month:'short',timeZone:'UTC'}):period.label}</th>)}</tr></thead><tbody>{rows.map(([label,line,style])=><tr key={`${line}-${label}`} className={style||''}><th>{label}</th>{periods.map((period,index)=><td key={period.label}>{line?format(line.includes(':')?detailValue(line,index):period[key][line]):''}</td>)}</tr>)}</tbody></table></div>
    <p className="statement-source">Sources: Revenue assumptions · Operating Expenses · Payroll &amp; Staffing · Loans · Working Capital · Fixed Assets</p></section>;
}
function FinancialStatementsView({projection}){return <div className="financial-statements-list"><FinancialStatementSection projection={projection} statement="income" title="Income Statement" number="1"/><FinancialStatementSection projection={projection} statement="cashflow" title="Cash Flow Statement" number="2"/><FinancialStatementSection projection={projection} statement="balance" title="Balance Sheet" number="3"/></div>}
function ResultChart({title,caption,values,labels}){const max=Math.max(...values.map(value=>Math.abs(value)),1);const points=values.map((value,index)=>`${values.length===1?50:index/(values.length-1)*100},${54-value/max*42}`).join(' ');return <div className="result-chart"><div><strong>{title}</strong><span>{caption}</span></div>{values.some(value=>value!==0)?<><svg viewBox="0 0 100 60" preserveAspectRatio="none" role="img" aria-label={`${title} chart`}><line x1="0" y1="54" x2="100" y2="54"/><polyline points={points}/></svg><div className="chart-axis"><span>{labels[0]}</span><b>{money(values.at(-1)||0)}</b><span>{labels.at(-1)}</span></div></>:<div className="chart-empty">No calculated data for this period</div>}</div>}
function BreakdownChart({title,items}){const total=items.reduce((sum,item)=>sum+item.value,0);return <div className="result-chart breakdown-chart"><div><strong>{title}</strong><span>Year 1</span></div>{total>0?<><div className="breakdown-bar">{items.map((item,index)=><i key={item.label} style={{width:`${item.value/total*100}%`,'--color':['#2e67d1','#18a47b','#e59b39','#805ad5'][index%4]}}/>)}</div><div className="breakdown-legend">{items.map((item,index)=><span key={item.label}><i style={{'--color':['#2e67d1','#18a47b','#e59b39','#805ad5'][index%4]}}/>{item.label}<b>{money(item.value)}</b></span>)}</div></>:<div className="chart-empty">No calculated data for this period</div>}</div>}
function ResultsTable({periods,monthlyView}){return <div className="results-table-wrap"><table className="results-table"><thead><tr><th>Period</th><th>Revenue</th><th>Gross profit</th><th>EBITDA</th><th>Net income</th><th>Closing cash</th><th>Loan balance</th></tr></thead><tbody>{periods.map(period=>{const monthly=monthlyView;return <tr key={monthly?period.date:period.label}><th>{monthly?new Date(`${period.date}T00:00:00Z`).toLocaleDateString('en-US',{month:'short',year:'numeric',timeZone:'UTC'}):period.label}</th><td>{money(monthly?period.totalRevenue:period.incomeStatement.revenue)}</td><td>{money(monthly?period.grossProfit:period.incomeStatement.grossProfit)}</td><td>{money(monthly?period.ebitda:period.incomeStatement.ebitda)}</td><td>{money(monthly?period.netIncome:period.incomeStatement.netIncome)}</td><td>{money(monthly?period.closingCash:period.cashFlowStatement.closingCash)}</td><td>{money(monthly?period.endingLoanBalances:period.balanceSheet.currentPortionOfDebt+period.balanceSheet.longTermDebt)}</td></tr>})}</tbody></table></div>}
function RevenueMix({years}) { const streams=Object.keys(years[0].streams||{}); const total=Object.values(years[0].streams||{}).reduce((a,b)=>a+b,0)||1; return <div className="finance-chart mix-chart"><div><strong>Revenue by stream</strong><span>Year 1 mix</span></div><div className="mix-bar">{streams.map((name,index)=><i key={name} style={{width:`${years[0].streams[name]/total*100}%`,background:['#2e67d1','#18a47b','#e59b39'][index%3]}}/>)}</div>{streams.map((name,index)=><small key={name}><i style={{background:['#2e67d1','#18a47b','#e59b39'][index%3]}}/>{name} · {percentValue(years[0].streams[name]/total)}</small>)}</div> }
function BreakEvenChart({months,breakEvenMonth}) { const expenses=months.map(row=>row.payroll+row.expenses); const max=Math.max(...months.map((row,index)=>Math.max(row.grossProfit,expenses[index])),1); return <div className="finance-chart break-chart"><div><strong>Break-even</strong><span>{breakEvenMonth?`Reached in month ${breakEvenMonth}`:'Not reached in forecast'}</span></div><div className="break-lines"><i style={{width:`${Math.min(100,(breakEvenMonth||36)/36*100)}%`}}/><b style={{left:`${Math.min(98,(breakEvenMonth||36)/36*100)}%`}}/></div><small>Gross profit crosses fixed operating costs</small></div> }
const percentValue=value=>(value*100).toFixed(0)+'%';

function Metric({label,value,trend}){return <div className="card metric"><span>{label}</span><strong>{value}</strong><small><Check size={13}/>{trend}</small></div>}

function completedSections(form){return PLAN_SECTIONS.filter(([key])=>form.sections?.[key]?.included&&form.sections[key].content?.trim())}
function PlanReview({form,review,go}){
 const sections=completedSections(form),years=review?.projection?.annual||[];
 return <div className="page review-plan"><PageHead eyebrow="STEP 4 OF 5" title="Review your complete business plan" copy="Check the cover details, complete index, written sections and calculated projections before downloading."/>
  <section className="paper review-cover"><span>BUSINESS PLAN</span><h1>{form.businessName||'Untitled Business'}</h1>{form.ownerName&&<p>Prepared by {form.ownerName}</p>}{form.location&&<p>{form.location}</p>}<p>{new Date().toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})}</p><button className="secondary" onClick={()=>go('info')}>Edit business information</button></section>
  <section className="paper review-index"><span className="eyebrow">COMPLETE PLAN INDEX</span><h2>Table of Contents</h2><ol>{sections.map(([,title],index)=><li key={title}><span>{index+1}. {title}</span><i/></li>)}<li className="financial-index"><span>{sections.length+1}. Financial Projections</span><i/></li></ol></section>
  {sections.length?sections.map(([key,title],index)=><section className="paper review-narrative" key={key}><div><span className="section-number">{String(index+1).padStart(2,'0')}</span><h2>{title}</h2><button onClick={()=>go('plan')}>Edit</button></div>{form.sections[key].content.split(/\n+/).filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}</section>):<section className="card empty-review"><p>No narrative sections have content yet.</p><button className="secondary" onClick={()=>go('plan')}>Add plan content</button></section>}
  <section className="paper review-financials"><div className="review-heading"><div><span className="eyebrow">{sections.length+1} · FINANCIAL PROJECTIONS</span><h2>Three-year financial overview</h2><p>Calculated from your revenue, expense, payroll, funding and financing assumptions.</p></div><button className="secondary" onClick={()=>go('financials')}>Edit financials</button></div>{years.length?<ResultsTable periods={years} monthlyView={false}/>:<p>Open Financial Projections to calculate your forecast.</p>}</section>
  <div className="page-actions"><button className="secondary" onClick={()=>go('financials')}><ArrowLeft/> Back to Financials</button><button className="primary" onClick={()=>go('download')}>Continue to Download <ArrowRight/></button></div>
 </div>
}
function DownloadPage({form,review,back,notify}){const valid=Boolean(review?.projection);const run=(fn,label)=>{if(!valid){notify('Review your financial projections first');return}fn(form,review);notify(`${label} downloaded`)};return <div className="page download-page"><PageHead eyebrow="STEP 5 OF 5" title="Your business plan is ready" copy="Download both files immediately. No signup, email address or payment is required."/><div className="download-grid"><article className="card download-card"><div className="download-icon pdf"><FileText/></div><h2>Download Business Plan PDF</h2><p>A polished business document with cover page, table of contents, completed narrative sections, financial projections and page numbers.</p><button className="primary" onClick={()=>run(downloadBusinessPlanPdf,'Business plan PDF')}><Download/> Download Business Plan PDF</button></article><article className="card download-card"><div className="download-icon excel"><FileSpreadsheet/></div><h2>Download Financial Projections Excel</h2><p>A real .xlsx workbook with assumptions, sources and uses, revenue, payroll, expenses and all three financial statements.</p><button className="primary excel-button" onClick={()=>run(downloadFinancialWorkbook,'Financial workbook')}><Download/> Download Financial Projections Excel</button></article></div><div className="download-assurance"><Check/> 100% free · Files are generated in your browser · Your information is not submitted</div><button className="secondary back-review" onClick={back}><ArrowLeft/> Back to Review</button></div>}
createRoot(document.getElementById('root')).render(<App/>);
